//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
  class O_FapovoArmy {
    author = "wlan0";
    addonRootClass = "PF_Factions";
    units[] = {
      "O_FapovoArmy_Officer_01",
      "O_FapovoArmy_Squad_Leader_01",
      "O_FapovoArmy_Team_Leader_01",
      "O_FapovoArmy_Rifleman_01",
      "O_FapovoArmy_Grenadier_01",
      "O_FapovoArmy_Autorifleman_01",
      "O_FapovoArmy_Marksman_01",
      "O_FapovoArmy_RTO_01",
      "O_FapovoArmy_Rifleman_AT_01",
      "O_FapovoArmy_Rifleman_AA_01",
      "O_FapovoArmy_Secret_Police_01",
      "O_FapovoArmy_Secret_Police_Sergeant_01",
      "O_FapovoArmy_Pilot_01",
      "O_FapovoArmy_Crewman_01",
      "O_FapovoArmy_Medic_01",
      "O_FapovoArmy_Rake_V5_01",
      "O_FapovoArmy_Rake_V5_HMG_01",
      "O_FapovoArmy_UH_95_Felix_01",
      "O_FapovoArmy_UH_101_Eagle_01",
      "O_FapovoArmy_M1015_Mule_01"
    };
    weapons[] = {};
    requiredVersion = 1.62;
    requiredAddons[] = { };
    
  };
};

class CfgFactionClasses {
  class O_FapovoArmy {
    displayName = "[PF] Fapovo Citizens Militia";
    side = 0;
    flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
    icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
    priority = 0;
  };
};

class CfgGroups {
  class EAST {

    class O_FapovoArmy {
      name = "[PF] Fapovo Citizens Militia";

      class Infantry {
        name = "Infantry";

        class o_fapovoarmy_infantry_fireteam {
          name = "Fireteam";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
        };

        class o_fapovoarmy_infantry_rifle_squad {
          name = "Rifle Squad";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Squad_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit5 {
            position[] = {15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit6 {
            position[] = {-15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit7 {
            position[] = {20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit8 {
            position[] = {-20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
        };

        class o_fapovoarmy_infantry_platoon_hq {
          name = "Platoon HQ";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "LIEUTENANT";
            side = 0;
            vehicle = "O_FapovoArmy_Officer_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_RTO_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Medic_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Marksman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_AT_01";
          };
        };

        class o_fapovoarmy_infantry_secret_police {
          name = "Secret Police";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Secret_Police_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Secret_Police_01";
          };
        };

        class o_fapovoarmy_infantry_motorized_rifle_squad {
          name = "Motorized Rifle Squad";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Squad_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit5 {
            position[] = {15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit6 {
            position[] = {-15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit7 {
            position[] = {20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit8 {
            position[] = {-20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit9 {
            position[] = {26,-44,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_M1015_Mule_01";
          };
        };

        class o_fapovoarmy_infantry_marksman_team {
          name = "Marksman Team";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Marksman_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
        };

        class o_fapovoarmy_infantry_anti_tank_team {
          name = "Anti-Tank Team";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_AT_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
        };

      };

      class SpecOps {
        name = "Special Forces";

      };

      class Motorized {
        name = "Motorized Infantry";

      };

      class Motorized_MTP {
        name = "Motorized Infantry (MTP)";

      };

      class Support {
        name = "Support Infantry";

      };

      class Mechanized {
        name = "Mechanized Infantry";

      };

      class Armored {
        name = "Armor";

      };

      class Artillery {
        name = "Artillery";

      };

      class Naval {
        name = "Naval";

      };

      class Air {
        name = "Air";

      };


    };

  };
};


//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_Rake_FRI_HMG;
    class LM_OPCAN_Rake_FRI_HMG_OCimport_01 : LM_OPCAN_Rake_FRI_HMG { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_Rake_FRI_HMG_OCimport_02 : LM_OPCAN_Rake_FRI_HMG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopTurret;
            class CodRiverTurret;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class LM_OPCAN_UH101_FRI;
    class LM_OPCAN_UH101_FRI_OCimport_01 : LM_OPCAN_UH101_FRI { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_UH101_FRI_OCimport_02 : LM_OPCAN_UH101_FRI_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_m1015_mule_cover_ins;
    class OPTRE_m1015_mule_cover_ins_OCimport_01 : OPTRE_m1015_mule_cover_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_m1015_mule_cover_ins_OCimport_02 : OPTRE_m1015_mule_cover_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_Rake_FRI_U;
    class LM_OPCAN_Rake_FRI_U_OCimport_01 : LM_OPCAN_Rake_FRI_U { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_Rake_FRI_U_OCimport_02 : LM_OPCAN_Rake_FRI_U_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_01;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class TCF_Felix_Rotary_Frieden;
    class TCF_Felix_Rotary_Frieden_OCimport_01 : TCF_Felix_Rotary_Frieden { scope = 0; class EventHandlers; class Turrets; };
    class TCF_Felix_Rotary_Frieden_OCimport_02 : TCF_Felix_Rotary_Frieden_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class O_FapovoArmy_Officer_01 : O_Soldier_F_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_blk","Koslovich_Red_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","Koslovich_Red_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_black_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_blk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30rnd_65x39_mag_msbs_JHP",4,30}}},{"B_LegStrapBag_black_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"Koslovich_Red_beret","41st_Shemagh_BlkMulticam",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Squad_Leader_01 : O_FapovoArmy_Officer_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McSurtr_UP",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Team_Leader_01 : O_FapovoArmy_Squad_Leader_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Rifleman_01 : O_FapovoArmy_Team_Leader_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Grenadier_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_GL_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_GL_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_GL_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{"1Rnd_HE_Grenade_shell",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"1Rnd_HE_Grenade_shell",6,1}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30},{"1Rnd_HE_Grenade_shell",2,1}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Autorifleman_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"MEU_CTAR_SAW","Binocular"};
        respawnWeapons[] = {"MEU_CTAR_SAW","Binocular"};

        magazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};
        respawnMagazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR_SAW","","","",{"100Rnd_580x42_Mag_F",100},{},""},{},{},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"100Rnd_580x42_Mag_F",1,100}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"100Rnd_580x42_Mag_F",3,100}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McValkyrie",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Marksman_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_Mark_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_Mark_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_Mark_sand_F","","","OPTRE_SRM_Sight",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"ACE_30Rnd_65_Creedmor_msbs_mag",4,30}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_RTO_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_RadioBag_01_hex_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_RadioBag_01_hex_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Medic_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_Kitbag_cbr";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_Kitbag_cbr",{{"ACE_splint",5},{"ACE_morphine",4},{"OPTRE_Biofoam",5},{"ACE_elasticBandage",3},{"ACE_adenosine",4},{"ACE_epinephrine",4},{"MEU_Medigel_Light",20},{"ACE_bodyBag",2},{"adv_aceCPR_AED",1},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_surgicalKit",1},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McGungnir_UP",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_medic'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_medic";

    };

    class O_FapovoArmy_Rifleman_AT_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","launch_MRAWS_sand_rail_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","launch_MRAWS_sand_rail_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","MRAWS_HEAT_F","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","MRAWS_HEAT_F","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_Kitbag_cbr";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{"launch_MRAWS_sand_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_Kitbag_cbr",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1},{"MRAWS_HEAT_F",3,1},{"MRAWS_HE_F",1,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Rifleman_AA_01 : O_FapovoArmy_Rifleman_AT_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AA)";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base_D";

        linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_sand_F","TCF_M57_Pilum","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_sand_F","TCF_M57_Pilum","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","TCF_2Rnd_50x137_HEAT","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","TCF_2Rnd_50x137_HEAT","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        backpack = "B_Kitbag_cbr";

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_sand_F","","","optic_ico_01_sand_f",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{"TCF_M57_Pilum","","","",{"TCF_2Rnd_50x137_HEAT",2},{},""},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{"B_Kitbag_cbr",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1},{"TCF_2Rnd_50x137_GUIDED",2,2}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Secret_Police_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Secret Police";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base";

        linkedItems[] = {"V_BandollierB_blk","TCF_MC_Regular","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","TCF_MC_Regular","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_UBS_black_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_UBS_black_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","6Rnd_12Gauge_Pellets","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","6Rnd_12Gauge_Pellets","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","6Rnd_12Gauge_Pellets","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","6Rnd_12Gauge_Pellets","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_UBS_black_F","","","MEU_REC_HOLO",{"30Rnd_65x39_caseless_msbs_mag",30},{"6Rnd_12Gauge_Pellets",6},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_blk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",2,30},{"6Rnd_12Gauge_Pellets",2,6}}},{},"TCF_MC_Regular","41st_Shemagh_McFenrir_UP",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Secret_Police_Sergeant_01 : O_FapovoArmy_Secret_Police_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Secret Police (Sergeant)";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "MEU_FRI_uni_Base";

        linkedItems[] = {"V_BandollierB_blk","Frieden_Grey_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","Frieden_Grey_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"arifle_MSBS65_black_F","hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"arifle_MSBS65_black_F","hgun_Rook40_F","Binocular"};

        magazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag","30Rnd_65x39_caseless_msbs_mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_MSBS65_black_F","","","MEU_REC_HOLO",{"30Rnd_65x39_caseless_msbs_mag",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base",{{"OPTRE_Biofoam",3},{"30Rnd_65x39_caseless_msbs_mag",2,30}}},{"V_BandollierB_blk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_65x39_caseless_msbs_mag",4,30}}},{},"Frieden_Grey_beret","41st_Shemagh_McSurtr",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Pilot_01 : O_FapovoArmy_Rifleman_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"OPCOS_CrewHelmet_CTRG_DES","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"OPCOS_CrewHelmet_CTRG_DES","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"Binocular"};
        respawnWeapons[] = {"Binocular"};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_Parachute";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_I_pilotCoveralls",{{"OPTRE_Biofoam",3}}},{},{"B_Parachute",{}},"OPCOS_CrewHelmet_CTRG_DES","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_Crewman_01 : O_FapovoArmy_Pilot_01 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "o_fapovoarmy";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

        uniformClass = "OPTRE_Ins_URF_Combat_Desert_Flat_Uniform";

        linkedItems[] = {"V_DeckCrew_brown_F","OPCOS_CrewHelmet_CTRG_DES","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"V_DeckCrew_brown_F","OPCOS_CrewHelmet_CTRG_DES","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"hgun_Rook40_F","Binocular"};
        respawnWeapons[] = {"hgun_Rook40_F","Binocular"};

        magazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"16Rnd_9x21_Mag","16Rnd_9x21_Mag"};

        backpack = "B_LegStrapBag_coyote_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"OPTRE_Ins_URF_Combat_Desert_Flat_Uniform",{{"OPTRE_Biofoam",3}}},{"V_DeckCrew_brown_F",{}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"OPCOS_CrewHelmet_CTRG_DES","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

    };

    class O_FapovoArmy_M1015_Mule_01 : OPTRE_m1015_mule_cover_ins_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1015 Mule";
        side = 0;
        faction = "o_fapovoarmy";
        crew = "O_FapovoArmy_Crewman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_f_beta\Truck_02\Data\Truck_02_kab_opfor_co.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_f_beta\Truck_02\Data\Truck_02_kuz_OPFOR_co.paa'];_unit setObjectTextureGlobal [2,'\a3\soft_f_beta\truck_02\data\truck_02_int_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Opfor";

    };

    class O_FapovoArmy_Rake_V5_01 : LM_OPCAN_Rake_FRI_U_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rake V-5";
        side = 0;
        faction = "O_FapovoArmy";
        crew = "O_FapovoArmy_Crewman_01";

        class Turrets : Turrets {
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = "O_FapovoArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_FapovoArmy_Rake_V5_HMG_01 : LM_OPCAN_Rake_FRI_HMG_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rake V-5 (HMG)";
        side = 0;
        faction = "o_fapovoarmy";
        crew = "O_FapovoArmy_Crewman_01";

        class Turrets : Turrets {
            class TopTurret : TopTurret { gunnerType = "O_FapovoArmy_Rifleman_01"; };
            class CodRiverTurret : CodRiverTurret { gunnerType = "O_FapovoArmy_Team_Leader_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_FapovoArmy_UH_101_Eagle_01 : LM_OPCAN_UH101_FRI_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-101 Eagle";
        side = 0;
        faction = "o_fapovoarmy";
        crew = "O_FapovoArmy_Pilot_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_FapovoArmy_Officer_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_FapovoArmy_UH_95_Felix_01 : TCF_Felix_Rotary_Frieden_OCimport_02 {
        author = "wlan0";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-95 Felix";
        side = 0;
        faction = "O_FapovoArmy";
        crew = "O_FapovoArmy_Pilot_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_FapovoArmy_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_FapovoArmy_Crewman_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_FapovoArmy_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
};
