//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgPatches {
  class O_FapovoArmy {
    author = "wlan0";
    addonRootClass = "PF_Factions";
    units[] = {
      "O_FapovoArmy_Officer_01",
      "O_FapovoArmy_Squad_Leader_01",
      "O_FapovoArmy_Team_Leader_01",
      "O_FapovoArmy_Rifleman_01",
      "O_FapovoArmy_Grenadier_01",
      "O_FapovoArmy_Autorifleman_01",
      "O_FapovoArmy_Marksman_01",
      "O_FapovoArmy_RTO_01",
      "O_FapovoArmy_Rifleman_AT_01",
      "O_FapovoArmy_Secret_Police_01",
      "O_FapovoArmy_Medic_01",
      "O_FapovoArmy_Rake_V5_01",
      "O_FapovoArmy_Rake_V5_HMG_01",
      "O_FapovoArmy_UH_101_Eagle_01",
      "O_FapovoArmy_M1015_Mule_01"
    };
    weapons[] = {};
    requiredVersion = 1.62;
    requiredAddons[] = { };
    
  };
};

class CfgFactionClasses {
  class O_FapovoArmy {
    displayName = "[PF] Fapovo Citizens Militia";
    side = 0;
    flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
    icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
    priority = 0;
  };
};

class CfgGroups {
  class EAST {

    class O_FapovoArmy {
      name = "[PF] Fapovo Citizens Militia";

      class Infantry {
        name = "Infantry";

        class o_fapovoarmy_infantry_fireteam {
          name = "Fireteam";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
        };

        class o_fapovoarmy_infantry_rifle_squad {
          name = "Rifle Squad";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Squad_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit5 {
            position[] = {15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit6 {
            position[] = {-15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit7 {
            position[] = {20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit8 {
            position[] = {-20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
        };

        class o_fapovoarmy_infantry_platoon_hq {
          name = "Platoon HQ";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "LIEUTENANT";
            side = 0;
            vehicle = "O_FapovoArmy_Officer_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_RTO_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Medic_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Marksman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_AT_01";
          };
        };

        class o_fapovoarmy_infantry_secret_police {
          name = "Secret Police";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Secret_Police_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Secret_Police_01";
          };
        };

        class o_fapovoarmy_infantry_motorized_rifle_squad {
          name = "Motorized Rifle Squad";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "SERGEANT";
            side = 0;
            vehicle = "O_FapovoArmy_Squad_Leader_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit2 {
            position[] = {-5,-5,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Team_Leader_01";
          };
          class Unit3 {
            position[] = {10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit4 {
            position[] = {-10,-10,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
          class Unit5 {
            position[] = {15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit6 {
            position[] = {-15,-15,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
          class Unit7 {
            position[] = {20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit8 {
            position[] = {-20,-20,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Autorifleman_01";
          };
          class Unit9 {
            position[] = {26,-44,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_M1015_Mule_01";
          };
        };

        class o_fapovoarmy_infantry_marksman_team {
          name = "Marksman Team";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Marksman_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_01";
          };
        };

        class o_fapovoarmy_infantry_anti_tank_team {
          name = "Anti-Tank Team";
          side = 0;
          faction = "O_FapovoArmy";
          icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
          rarityGroup = 0.5;

          class Unit0 {
            position[] = {0,0,0};
            rank = "CORPORAL";
            side = 0;
            vehicle = "O_FapovoArmy_Rifleman_AT_01";
          };
          class Unit1 {
            position[] = {5,-5,0};
            rank = "PRIVATE";
            side = 0;
            vehicle = "O_FapovoArmy_Grenadier_01";
          };
        };

      };

      class SpecOps {
        name = "Special Forces";

      };

      class Motorized {
        name = "Motorized Infantry";

      };

      class Motorized_MTP {
        name = "Motorized Infantry (MTP)";

      };

      class Support {
        name = "Support Infantry";

      };

      class Mechanized {
        name = "Mechanized Infantry";

      };

      class Armored {
        name = "Armor";

      };

      class Artillery {
        name = "Artillery";

      };

      class Naval {
        name = "Naval";

      };

      class Air {
        name = "Air";

      };


    };

  };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

  class O_Soldier_F;
  class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };

  class LM_OPCAN_Rake_FRI_U;
  class LM_OPCAN_Rake_FRI_U_OCimport_01 : LM_OPCAN_Rake_FRI_U { scope = 0; class EventHandlers; class Turrets; };
  class LM_OPCAN_Rake_FRI_U_OCimport_02 : LM_OPCAN_Rake_FRI_U_OCimport_01 { 
    class EventHandlers; 
    class Turrets : Turrets {
      class CargoTurret_02;
      class CargoTurret_03;
      class CargoTurret_01;
      class CargoTurret_04;
      class CargoTurret_05;
      class CargoTurret_06;
    };
  };

  class LM_OPCAN_Rake_FRI_HMG;
  class LM_OPCAN_Rake_FRI_HMG_OCimport_01 : LM_OPCAN_Rake_FRI_HMG { scope = 0; class EventHandlers; class Turrets; };
  class LM_OPCAN_Rake_FRI_HMG_OCimport_02 : LM_OPCAN_Rake_FRI_HMG_OCimport_01 { 
    class EventHandlers; 
    class Turrets : Turrets {
      class TopTurret;
      class CodRiverTurret;
      class CargoTurret_02;
      class CargoTurret_03;
    };
  };

  class LM_OPCAN_UH101_FRI;
  class LM_OPCAN_UH101_FRI_OCimport_01 : LM_OPCAN_UH101_FRI { scope = 0; class EventHandlers; class Turrets; };
  class LM_OPCAN_UH101_FRI_OCimport_02 : LM_OPCAN_UH101_FRI_OCimport_01 { 
    class EventHandlers; 
    class Turrets : Turrets {
      class MainTurret;
    };
  };

  class OPTRE_m1015_mule_cover_ins;
  class OPTRE_m1015_mule_cover_ins_OCimport_01 : OPTRE_m1015_mule_cover_ins { scope = 0; class EventHandlers; class Turrets; };
  class OPTRE_m1015_mule_cover_ins_OCimport_02 : OPTRE_m1015_mule_cover_ins_OCimport_01 { 
    class EventHandlers; 
    class Turrets : Turrets {
      class CargoTurret_01;
      class CargoTurret_02;
    };
  };


  class O_FapovoArmy_Officer_01 : O_Soldier_F_OCimport_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Officer";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base";

    linkedItems[] = {"V_BandollierB_blk","Koslovich_Red_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_blk","Koslovich_Red_beret","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_black_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_blk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30rnd_580x42_mag_JHP",6,30}}},{"B_LegStrapBag_black_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"Koslovich_Red_beret","41st_Shemagh_BlkMulticam",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;
    ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

  };

  class O_FapovoArmy_Squad_Leader_01 : O_FapovoArmy_Officer_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Squad Leader";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McSurtr_UP",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_emblems_uprising'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;
    ALiVE_orbatCreator_insignia = "OPTRE_Insignia_emblems_uprising";

  };

  class O_FapovoArmy_Team_Leader_01 : O_FapovoArmy_Squad_Leader_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Team Leader";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Rifleman_01 : O_FapovoArmy_Team_Leader_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Rifleman";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Grenadier_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Grenadier";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR_GL","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR_GL","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","1Rnd_HE_Grenade_shell","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR_GL","","","",{"30Rnd_580x42_Mag_F",30},{"1Rnd_HE_Grenade_shell",1},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"1Rnd_HE_Grenade_shell",3,1}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1},{"1Rnd_HE_MEU_shell",5,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Autorifleman_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Autorifleman";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR_SAW","Binocular"};
    respawnWeapons[] = {"MEU_CTAR_SAW","Binocular"};

    magazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};
    respawnMagazines[] = {"100Rnd_580x42_Mag_F","100Rnd_580x42_Mag_F"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR_SAW","","","",{"100Rnd_580x42_Mag_F",100},{},""},{},{},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"100Rnd_580x42_Mag_F",1,100}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"100Rnd_580x42_Mag_F",3,100}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McValkyrie",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Marksman_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Marksman";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"srifle_DMR_06_camo_F","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"srifle_DMR_06_camo_F","hgun_Rook40_F","Binocular"};

    magazines[] = {"20Rnd_762x51_Mag","16Rnd_9x21_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"20Rnd_762x51_Mag","16Rnd_9x21_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag"};

    backpack = "B_LegStrapBag_coyote_F";

    ALiVE_orbatCreator_loadout[] = {{"srifle_DMR_06_camo_F","","","OPTRE_SRM_Sight",{"20Rnd_762x51_Mag",20},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"20Rnd_762x51_Mag",2,20}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"20Rnd_762x51_Mag",4,20}}},{"B_LegStrapBag_coyote_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_RTO_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "RTO";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"SMG_05_F","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"SMG_05_F","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag","30Rnd_9x21_Mag_SMG_02","16Rnd_9x21_Mag"};

    backpack = "B_RadioBag_01_hex_F";

    ALiVE_orbatCreator_loadout[] = {{"SMG_05_F","","","",{"30Rnd_9x21_Mag_SMG_02",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_9x21_Mag_SMG_02",2,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30Rnd_9x21_Mag_SMG_02",4,30}}},{"B_RadioBag_01_hex_F",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Rifleman_AT_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Rifleman (AT)";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","launch_MRAWS_sand_rail_F","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","launch_MRAWS_sand_rail_F","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","MRAWS_HEAT_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","MRAWS_HEAT_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_Kitbag_cbr";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{"launch_MRAWS_sand_rail_F","","","",{"MRAWS_HEAT_F",1},{},""},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17}}},{"B_Kitbag_cbr",{{"ACE_splint",2},{"ACE_morphine",1},{"ACE_MapTools",1},{"ACE_CableTie",5},{"OPTRE_Biofoam",1},{"ACE_quikclot",3},{"ACE_packingBandage",3},{"ACE_elasticBandage",3},{"ACE_fieldDressing",3},{"ACE_adenosine",1},{"ACE_epinephrine",1},{"MEU_Medigel_Light",5},{"SmokeShellBlue",1,1},{"HandGrenade",2,1},{"MRAWS_HEAT_F",3,1},{"MRAWS_HE_F",1,1}}},"LM_MEU_Frihelm_D","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Secret_Police_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Secret Police";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base";

    linkedItems[] = {"V_BandollierB_blk","TCF_MC_Regular","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_blk","TCF_MC_Regular","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_blk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17},{"30rnd_580x42_mag_JHP",6,30}}},{},"TCF_MC_Regular","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_Medic_01 : O_FapovoArmy_Rifleman_01 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Medic";
    side = 0;
    faction = "O_FapovoArmy";

    identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlasses"};

    uniformClass = "MEU_FRI_uni_Base_D";

    linkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
    respawnlinkedItems[] = {"V_BandollierB_khk","LM_MEU_Frihelm_D","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

    weapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};
    respawnWeapons[] = {"MEU_CTAR","hgun_Rook40_F","Binocular"};

    magazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};
    respawnMagazines[] = {"30Rnd_580x42_Mag_F","16Rnd_9x21_Mag","30Rnd_580x42_Mag_F","16Rnd_9x21_Mag"};

    backpack = "B_Kitbag_cbr";

    ALiVE_orbatCreator_loadout[] = {{"MEU_CTAR","","","",{"30Rnd_580x42_Mag_F",30},{},""},{},{"hgun_Rook40_F","","","",{"16Rnd_9x21_Mag",17},{},""},{"MEU_FRI_uni_Base_D",{{"OPTRE_Biofoam",3},{"30Rnd_580x42_Mag_F",3,30}}},{"V_BandollierB_khk",{{"Chemlight_green",2,1},{"OPTRE_M9_Frag",2,1},{"16Rnd_9x21_Mag",2,17}}},{"B_Kitbag_cbr",{{"ACE_splint",5},{"ACE_morphine",4},{"OPTRE_Biofoam",5},{"ACE_elasticBandage",3},{"ACE_adenosine",4},{"ACE_epinephrine",4},{"MEU_Medigel_Light",20},{"ACE_bodyBag",2},{"adv_aceCPR_AED",1},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_surgicalKit",1},{"SmokeShellBlue",1,1},{"HandGrenade",2,1}}},"LM_MEU_Frihelm_D","41st_Shemagh_McGungnir_UP",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'OPTRE_Insignia_medic'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;
    ALiVE_orbatCreator_insignia = "OPTRE_Insignia_medic";

  };

  class O_FapovoArmy_Rake_V5_01 : LM_OPCAN_Rake_FRI_U_OCimport_02 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Rake V-5";
    side = 0;
    faction = "O_FapovoArmy";
    crew = "O_FapovoArmy_Team_Leader_01";

    class Turrets : Turrets {
      class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_FapovoArmy_Rifleman_01"; };
      class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
      class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
      class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
      class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
      class CargoTurret_06 : CargoTurret_06 { gunnerType = "O_FapovoArmy_Autorifleman_01"; };
    };



    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'LM_OPCAN3.0\OPF\FRI\VEH\Rake_FRI.paa'];_unit setObjectTextureGlobal [1,'a3\Soft_F_Exp\LSV_01\Data\NATO_LSV_02_black_CO.paa'];_unit setObjectTextureGlobal [2,'a3\Soft_F_Exp\LSV_01\Data\NATO_LSV_03_black_CO.paa'];_unit setObjectTextureGlobal [3,'a3\Soft_F_Exp\LSV_01\Data\NATO_LSV_Adds_black_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;
    ALiVE_orbatCreator_texture = "FRI";

  };

  class O_FapovoArmy_Rake_V5_HMG_01 : LM_OPCAN_Rake_FRI_HMG_OCimport_02 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "Rake V-5 (HMG)";
    side = 0;
    faction = "O_FapovoArmy";
    crew = "O_FapovoArmy_Rifleman_01";

    class Turrets : Turrets {
      class TopTurret : TopTurret { gunnerType = "O_FapovoArmy_Rifleman_01"; };
      class CodRiverTurret : CodRiverTurret { gunnerType = "O_FapovoArmy_Team_Leader_01"; };
      class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
      class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
    };



    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_UH_101_Eagle_01 : LM_OPCAN_UH101_FRI_OCimport_02 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "UH-101 Eagle";
    side = 0;
    faction = "O_FapovoArmy";
    crew = "O_FapovoArmy_Officer_01";

    class Turrets : Turrets {
      class MainTurret : MainTurret { gunnerType = "O_FapovoArmy_Officer_01"; };
    };



    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

  class O_FapovoArmy_M1015_Mule_01 : OPTRE_m1015_mule_cover_ins_OCimport_02 {
    author = "wlan0";
    scope = 2;
    scopeCurator = 2;
    displayName = "M1015 Mule";
    side = 0;
    faction = "O_FapovoArmy";
    crew = "O_FapovoArmy_Rifleman_01";

    class Turrets : Turrets {
      class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
      class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
    };



    class EventHandlers : EventHandlers {
      class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

      class ALiVE_orbatCreator {
        init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
      };

    };

    // custom attributes (do not delete)
    ALiVE_orbatCreator_owned = 1;

  };

};