/**
 * AUTOGENERATED FILE. Edit config.cpp.tpl or generator.ts instead. Any changes to this file will be overwritten otherwise.
 */

class CfgPatches
{
  class WS_Props_TicTacs
  {
    author = "wlan0";
    addonRootClass = "WS_Props";
    requiredVersion = 0.1;
    units[] =
    {
      "1st_MEU_patch_vehicles_supplypods", // to override 1stMEU and make sure our tictacs don't get overwritten
      "WS_Props_TicTac_Empty",
      "WS_Props_TicTac_MA40",
      "WS_Props_TicTac_MA40_UGL",
      "WS_Props_TicTac_MA40___Resupply",
      "WS_Props_TicTac_MA40_UGL___Resupply",
      "WS_Props_TicTac_M7",
      "WS_Props_TicTac_M7___Resupply",
      "WS_Props_TicTac_AU_44_Mortar",
      "WS_Props_TicTac_AU_44_Mortar___Ammunition",
      "WS_Props_TicTac_Medical",
      "WS_Props_TicTac_Recon_Drones",
    };
    weapons[] = { };
  };
};

class CfgVehicles
{
  class OPTRE_Ammo_SupplyPod_Empty;
  class WS_Props_TicTac_Empty : OPTRE_Ammo_SupplyPod_Empty
  {
    scope = 1;
    dlc = "WS";
    author = "wlan0";
    displayName = "[WS] Supply Pod (Empty)";
    maximumLoad = 1000000;
    hiddenSelections[] =
    {
      "camo",
    };
    hiddenSelectionsTextures[] =
    {
      "WS_Props\Tictacs\_textures\pods\blank.paa",
    };
    editorPreview = "WS_Props\Tictacs\_textures\previews\blank.jpg";

    class TransportItems { };
    class TransportMagazines { };
    class TransportWeapons { };
  };

  class WS_Props_TicTac_MA40: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (MA40)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\ma40.paa" };
    class TransportItems
    {
      class _xx_TCP_optic_EVOSJ1 { name = "TCP_optic_EVOSJ1"; count = 1; }
      class _xx_TCP_acc_pointer_lam_MA40 { name = "TCP_acc_pointer_lam_MA40"; count = 1; }
      class _xx_TCP_muzzle_brake_762_01 { name = "TCP_muzzle_brake_762_01"; count = 1; }
    };
    class TransportWeapons
    {
      class _xx_TCP_arifle_MA40 { weapon = "TCP_arifle_MA40"; count = 1; }
    };
    class TransportMagazines
    {
      class _xx_TCP_36Rnd_762x51_Mag { magazine = "TCP_36Rnd_762x51_Mag"; count = 7; }
      class _xx_TCP_36Rnd_762x51_Mag_Dual { magazine = "TCP_36Rnd_762x51_Mag_Dual"; count = 7; }
    };
  };

  class WS_Props_TicTac_MA40_UGL: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (MA40 UGL)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\ma40gl.paa" };
    class TransportItems
    {
      class _xx_TCP_optic_EVOSJ1 { name = "TCP_optic_EVOSJ1"; count = 1; }
      class _xx_TCP_acc_pointer_lam_MA40 { name = "TCP_acc_pointer_lam_MA40"; count = 1; }
      class _xx_TCP_muzzle_brake_762_01 { name = "TCP_muzzle_brake_762_01"; count = 1; }
    };
    class TransportWeapons
    {
      class _xx_TCP_arifle_MA40_GL { weapon = "TCP_arifle_MA40_GL"; count = 1; }
    };
    class TransportMagazines
    {
      class _xx_TCP_36Rnd_762x51_Mag { magazine = "TCP_36Rnd_762x51_Mag"; count = 4; }
      class _xx_TCP_36Rnd_762x51_Mag_Dual { magazine = "TCP_36Rnd_762x51_Mag_Dual"; count = 4; }
      class _xx_TCP_1Rnd_40_Shell_HE { magazine = "TCP_1Rnd_40_Shell_HE"; count = 10; }
      class _xx_TCP_1Rnd_40_Shell_TD { magazine = "TCP_1Rnd_40_Shell_TD"; count = 2; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_White { magazine = "TCP_1Rnd_40_Shell_Smoke_White"; count = 2; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_Red { magazine = "TCP_1Rnd_40_Shell_Smoke_Red"; count = 2; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_Blue { magazine = "TCP_1Rnd_40_Shell_Smoke_Blue"; count = 2; }
    };
  };

  class WS_Props_TicTac_MA40___Resupply: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (MA40 | Resupply)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\ma40_ammo.paa" };
    class TransportMagazines
    {
      class _xx_TCP_36Rnd_762x51_Mag { magazine = "TCP_36Rnd_762x51_Mag"; count = 21; }
      class _xx_TCP_36Rnd_762x51_Mag_Dual { magazine = "TCP_36Rnd_762x51_Mag_Dual"; count = 21; }
      class _xx_TCP_36Rnd_762x51_Mag_Tracer_Green { magazine = "TCP_36Rnd_762x51_Mag_Tracer_Green"; count = 7; }
      class _xx_TCP_36Rnd_762x51_Mag_Tracer_DIM { magazine = "TCP_36Rnd_762x51_Mag_Tracer_DIM"; count = 7; }
    };
  };

  class WS_Props_TicTac_MA40_UGL___Resupply: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (MA40 UGL | Resupply)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\ma40gl_ammo.paa" };
    class TransportMagazines
    {
      class _xx_TCP_36Rnd_762x51_Mag { magazine = "TCP_36Rnd_762x51_Mag"; count = 7; }
      class _xx_TCP_36Rnd_762x51_Mag_Dual { magazine = "TCP_36Rnd_762x51_Mag_Dual"; count = 7; }
      class _xx_TCP_36Rnd_762x51_Mag_Tracer_Green { magazine = "TCP_36Rnd_762x51_Mag_Tracer_Green"; count = 3; }
      class _xx_TCP_36Rnd_762x51_Mag_Tracer_DIM { magazine = "TCP_36Rnd_762x51_Mag_Tracer_DIM"; count = 3; }
      class _xx_TCP_1Rnd_40_Shell_HE { magazine = "TCP_1Rnd_40_Shell_HE"; count = 20; }
      class _xx_TCP_1Rnd_40_Shell_TD { magazine = "TCP_1Rnd_40_Shell_TD"; count = 8; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_White { magazine = "TCP_1Rnd_40_Shell_Smoke_White"; count = 5; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_Red { magazine = "TCP_1Rnd_40_Shell_Smoke_Red"; count = 5; }
      class _xx_TCP_1Rnd_40_Shell_Smoke_Blue { magazine = "TCP_1Rnd_40_Shell_Smoke_Blue"; count = 5; }
      class _xx_TCP_1Rnd_40_Shell_Signal_White { magazine = "TCP_1Rnd_40_Shell_Signal_White"; count = 3; }
      class _xx_TCP_1Rnd_40_Shell_Signal_Red { magazine = "TCP_1Rnd_40_Shell_Signal_Red"; count = 3; }
      class _xx_TCP_1Rnd_40_Shell_Signal_Green { magazine = "TCP_1Rnd_40_Shell_Signal_Green"; count = 3; }
    };
  };

  class WS_Props_TicTac_M7: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (M7)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\m7.paa" };
    class TransportItems
    {
      class _xx_TCP_optic_M5BSLSV_Blue { name = "TCP_optic_M5BSLSV_Blue"; count = 1; }
      class _xx_TCP_acc_pointer_lam_M7 { name = "TCP_acc_pointer_lam_M7"; count = 1; }
      class _xx_TCP_muzzle_snds_523_01 { name = "TCP_muzzle_snds_523_01"; count = 1; }
    };
    class TransportWeapons
    {
      class _xx_TCP_SMG_M7 { weapon = "TCP_SMG_M7"; count = 1; }
    };
    class TransportMagazines
    {
      class _xx_TCP_48Rnd_5x23_Mag_JHP { magazine = "TCP_48Rnd_5x23_Mag_JHP"; count = 7; }
      class _xx_TCP_48Rnd_5x23_Mag_AP { magazine = "TCP_48Rnd_5x23_Mag_AP"; count = 7; }
      class _xx_TCP_48Rnd_5x23_Mag { magazine = "TCP_48Rnd_5x23_Mag"; count = 7; }
    };
  };

  class WS_Props_TicTac_M7___Resupply: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (M7 | Resupply)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\m7_ammo.paa" };
    class TransportMagazines
    {
      class _xx_TCP_48Rnd_5x23_Mag_JHP { magazine = "TCP_48Rnd_5x23_Mag_JHP"; count = 21; }
      class _xx_TCP_48Rnd_5x23_Mag_AP { magazine = "TCP_48Rnd_5x23_Mag_AP"; count = 21; }
      class _xx_TCP_48Rnd_5x23_Mag { magazine = "TCP_48Rnd_5x23_Mag"; count = 21; }
    };
  };

  class WS_Props_TicTac_AU_44_Mortar: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (AU-44 Mortar)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\au44.paa" };
    class TransportItems
    {
      class _xx_OPTRE_CSW_AU44_Mortar_Carry { name = "OPTRE_CSW_AU44_Mortar_Carry"; count = 1; }
    };
    class TransportWeapons
    {
      class _xx_OPTRE_CSW_AU44_Carry_Baseplate { weapon = "OPTRE_CSW_AU44_Carry_Baseplate"; count = 1; }
    };
  };

  class WS_Props_TicTac_AU_44_Mortar___Ammunition: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (AU-44 Mortar | Ammunition)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\au44_ammo.paa" };
    class TransportMagazines
    {
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_shells { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_shells"; count = 40; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_Cluster_HE { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_Cluster_HE"; count = 5; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_guided { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_guided"; count = 8; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_LG { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_LG"; count = 8; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_Smoke_white { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_Smoke_white"; count = 10; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_Flare_white { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_Flare_white"; count = 5; }
      class _xx_OPTRE_CSW_1Rnd_122mm_Mo_IR_Flare_white { magazine = "OPTRE_CSW_1Rnd_122mm_Mo_IR_Flare_white"; count = 5; }
    };
  };

  class WS_Props_TicTac_Medical: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (Medical)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\medical.paa" };
    class TransportItems
    {
      class _xx_OPTRE_Biofoam { name = "OPTRE_Biofoam"; count = 40; }
    };
  };

  class WS_Props_TicTac_Recon_Drones: WS_Props_TicTac_Empty
  {
    scope = 2;
    displayName = "[WS] Supply Pod (Recon Drones)";
    hiddenSelectionsTextures[] = { "WS_Props\Tictacs\_textures\pods\drone.paa" };
    class TransportItems
    {
      class _xx_MEU_Raven_Drone_Item { name = "MEU_Raven_Drone_Item"; count = 1; }
      class _xx_OPTRE_OQ_38_Wren_Drone_Item { name = "OPTRE_OQ_38_Wren_Drone_Item"; count = 1; }
      class _xx_OPTRE_OQ40_Minibee_Drone_Black_Item { name = "OPTRE_OQ40_Minibee_Drone_Black_Item"; count = 1; }
      class _xx_ACE_UAVBattery { name = "ACE_UAVBattery"; count = 6; }
    };
  };
};
