class CfgPatches {
    class O_USGuard_OD {
        units[] = {
            "O_USNG_Crewman_01",
            "O_USNG_Rifleman_01",
            "O_USGuard_Machine_Gunner_OD_01",
            "O_USGuard_Shotgun_OD_01",
            "O_USGuard_Team_Leader_OD_01",
            "O_USGuard_Officer_OD_01",
            "O_OUSGuardOD_M38A2_Covered_01",
            "O_OUSGuardOD_M38A2_Ammo_01",
            "O_OUSGuardOD_M38A2_Fuel_01",
            "O_OUSGuardOD_M38A2_Open_01",
            "O_OUSGuardOD_M223_Unarmed_01",
            "O_OUSGuardOD_M223_Armed_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "O_USArmy_DES",
            "A3_Characters_F",
            "CUP_Creatures_Military_RussiaModern_Uniforms",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "Webs_Footsteps",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_expansion_uk",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "lambs_range",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "AlkFrameWork_Default_UI",
            "CUP_Core",
            "cba_xeh",
            "CUP_WheeledVehicles_Ural",
            "A3_Soft_F",
            "A3_Soft_F_Beta_Truck_01",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_01",
            "A3_Soft_F_Gamma_Van_01",
            "A3_Soft_F_EPC_Truck_03",
            "A3_Soft_F_Orange_Van_02",
            "rhs_c_zil131",
            "rhs_c_a2port_car",
            "rhs_c_kamaz",
            "rhs_c_kraz255",
            "rhs_c_rva",
            "rhsusf_c_Caiman",
            "rhsusf_c_fmtv",
            "rhsusf_c_HEMTT_A4",
            "rhsusf_c_himars",
            "rhsusf_c_mtvr",
            "cwr3_vehicle_bus",
            "ace_repair",
            "rhssaf_c_vehicles",
            "ace_cargo",
            "rhsgref_c_vehicles_ret",
            "cwr3_vehicle_m939",
            "CUP_WheeledVehicles_RM70",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "mrb_a3_vehiclevisibility",
            "cwr3_vehicle_scud",
            "A3_Data_F_ParticleEffects",
            "ace_compat_rhs_afrf3",
            "ace_interaction",
            "ace_tagging",
            "ace_vehicles",
            "A3_Armor_F_Beta",
            "ace_compat_cup_vehicles_refuel",
            "CUP_WheeledVehicles_GAZTigr"
        };
        author = "[2LT] O'Neill (He/Him)";
        authors[] = {"[2LT] O'Neill (He/Him)"};
        addonRootClass = "NASR_Factions";
    };
};
//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_USGuard_OD {
        displayName = "[PF] USA (Guard)";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_USGuard_OD {
            name = "[PF] USA (Guard)";

            class Infantry {
                name = "Infantry";

                class o_ousguardod_infantry_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                };

                class o_ousguardod_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                };

                class o_ousguardod_infantry_heavy_fireteam {
                    name = "Heavy Fireteam";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Machine_Gunner_OD_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                };

                class o_ousguardod_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_USGuard_Officer_OD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

                class o_ousguardod_motorized_rifle_squad {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_USGuard_Officer_OD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSGuardOD_M38A2_Covered_01";
                    };
                };

                class o_ousguardod_motorized_rifle_squad_with_escort {
                    name = "Rifle Squad with Escort";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_USGuard_Officer_OD_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_USGuard_Team_Leader_OD_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USNG_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_USGuard_Shotgun_OD_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSGuardOD_M38A2_Covered_01";
                    };
                    class Unit9 {
                        position[] = {25,-29,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSGuardOD_M223_Armed_01";
                    };
                };

                class o_ousguardod_motorized_m223_patrol {
                    name = "M223 Patrol";
                    side = 0;
                    faction = "o_usguard_od";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSGuardOD_M223_Armed_01";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSGuardOD_M223_Armed_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_OUSArmyDES_Crewman_01;
    class O_OUSArmyDES_Crewman_01_OCimport_01 : O_OUSArmyDES_Crewman_01 { scope = 0; class EventHandlers; };
    class O_OUSArmyDES_Crewman_01_OCimport_02 : O_OUSArmyDES_Crewman_01_OCimport_01 { class EventHandlers; };

    class O_OUSArmyDES_Rifleman_01;
    class O_OUSArmyDES_Rifleman_01_OCimport_01 : O_OUSArmyDES_Rifleman_01 { scope = 0; class EventHandlers; };
    class O_OUSArmyDES_Rifleman_01_OCimport_02 : O_OUSArmyDES_Rifleman_01_OCimport_01 { class EventHandlers; };

    class CUP_B_Ural_AFU;
    class CUP_B_Ural_AFU_OCimport_01 : CUP_B_Ural_AFU { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_Ural_AFU_OCimport_02 : CUP_B_Ural_AFU_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class CUP_B_Ural_Reammo_AFU;
    class CUP_B_Ural_Reammo_AFU_OCimport_01 : CUP_B_Ural_Reammo_AFU { scope = 0; class EventHandlers; };
    class CUP_B_Ural_Reammo_AFU_OCimport_02 : CUP_B_Ural_Reammo_AFU_OCimport_01 { scope = 0; class EventHandlers; };

    class CUP_B_Ural_Refuel_AFU;
    class CUP_B_Ural_Refuel_AFU_OCimport_01 : CUP_B_Ural_Refuel_AFU { scope = 0; class EventHandlers; };
    class CUP_B_Ural_Refuel_AFU_OCimport_02 : CUP_B_Ural_Refuel_AFU_OCimport_01 { scope = 0; class EventHandlers; };

    class CUP_B_Ural_Open_AFU;
    class CUP_B_Ural_Open_AFU_OCimport_01 : CUP_B_Ural_Open_AFU { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_Ural_Open_AFU_OCimport_02 : CUP_B_Ural_Open_AFU_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class CUP_B_Tigr_233011_GREEN_AFU;
    class CUP_B_Tigr_233011_GREEN_AFU_OCimport_01 : CUP_B_Tigr_233011_GREEN_AFU { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_Tigr_233011_GREEN_AFU_OCimport_02 : CUP_B_Tigr_233011_GREEN_AFU_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurretTurnIn;
            class MainTurretFFV;
            class SecTurretTurnIn;
            class SecTurretFFV;
        };
    };

    class CUP_B_Tigr_233014_PK_GREEN_AFU;
    class CUP_B_Tigr_233014_PK_GREEN_AFU_OCimport_01 : CUP_B_Tigr_233014_PK_GREEN_AFU { scope = 0; class EventHandlers; class Turrets; };
    class CUP_B_Tigr_233014_PK_GREEN_AFU_OCimport_02 : CUP_B_Tigr_233014_PK_GREEN_AFU_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class MainTurretTurnIn;
        };
    };


    class O_USNG_Crewman_01 : O_OUSArmyDES_Crewman_01_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107";

        linkedItems[] = {"cwr3_b_vest_alice_crew","CUP_H_PMC_Beanie_Khaki","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_crew","CUP_H_PMC_Beanie_Khaki","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"cwr3_b_uniform_og107",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_15Rnd_9x19_M9",3,15}}},{"cwr3_b_vest_alice_crew",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_15Rnd_9x19_M9",5,15}}},{},"CUP_H_PMC_Beanie_Khaki","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_USNG_Rifleman_01 : O_OUSArmyDES_Rifleman_01_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107";

        linkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_cover_net","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_cover_net","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A1","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A1","Binocular"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{},{"cwr3_b_uniform_og107",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_20Rnd_556x45_Stanag",3,20}}},{"cwr3_b_vest_alice",{{"ACE_fieldDressing",5},{"ACE_quikclot",2},{"ACE_packingBandage",5},{"ACE_CableTie",5},{"ACE_Canteen",2},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1},{"ACE_surgicalKit",1},{"ACE_splint",1},{"ACE_tourniquet",2},{"CUP_20Rnd_556x45_Stanag",7,20},{"ACE_CTS9",2,1},{"SmokeShellBlue",1,1},{"SmokeShellGreen",1,1}}},{},"cwr3_b_headgear_m1_cover_net","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_USGuard_Machine_Gunner_OD_01 : O_USNG_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107";

        linkedItems[] = {"cwr3_b_vest_alice_mg","cwr3_b_headgear_m1_cover_net","ItemMap","ItemRadio","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_mg","cwr3_b_headgear_m1_cover_net","ItemMap","ItemRadio","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_lmg_M60E4_norail"};
        respawnWeapons[] = {"CUP_lmg_M60E4_norail"};

        magazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};
        respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M","CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M"};

        backpack = "usm_pack_762x51_bandoliers";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_M60E4_norail","","","",{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",100},{},""},{},{},{"cwr3_b_uniform_og107",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice_mg",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_100Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",2,100}}},{"usm_pack_762x51_bandoliers",{{"ACE_elasticBandage",5},{"ACE_fieldDressing",5},{"ACE_quikclot",2},{"ACE_CableTie",5},{"ACE_Canteen",2},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1},{"ACE_surgicalKit",1},{"ACE_rope27",1},{"CUP_100Rnd_TE4_LRT4_White_Tracer_762x51_Belt_M",1,100},{"CUP_100Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",2,100}}},"cwr3_b_headgear_m1_cover_net","",{},{"ItemMap","","ItemRadio","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_USGuard_Shotgun_OD_01 : O_USGuard_Machine_Gunner_OD_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shotgun";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107";

        linkedItems[] = {"cwr3_b_vest_alice_ar","cwr3_b_headgear_m1_cover_net","ItemMap","ItemRadio","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_ar","cwr3_b_headgear_m1_cover_net","ItemMap","ItemRadio","ItemCompass","Itemwatch"};

        weapons[] = {"rhs_weap_M590_5RD"};
        respawnWeapons[] = {"rhs_weap_M590_5RD"};

        magazines[] = {"rhsusf_5Rnd_00Buck","rhsusf_5Rnd_00Buck"};
        respawnMagazines[] = {"rhsusf_5Rnd_00Buck","rhsusf_5Rnd_00Buck"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_M590_5RD","","","",{"rhsusf_5Rnd_00Buck",5},{},""},{},{},{"cwr3_b_uniform_og107",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"rhsusf_5Rnd_00Buck",3,5}}},{"cwr3_b_vest_alice_ar",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"ACE_fieldDressing",5},{"ACE_quikclot",2},{"ACE_elasticBandage",5},{"ACE_Flashlight_XL50",1},{"ACE_surgicalKit",1},{"ACE_EntrenchingTool",1},{"ACE_CableTie",5},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"rhsusf_5Rnd_00Buck",10,5},{"rhsusf_5Rnd_Slug",4,5}}},{},"cwr3_b_headgear_m1_cover_net","",{},{"ItemMap","","ItemRadio","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_USGuard_Team_Leader_OD_01 : O_USNG_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_cap_m81_woodland_early","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_cap_m81_woodland_early","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A1","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A1","Binocular"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{},{"cwr3_b_uniform_og107",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_20Rnd_556x45_Stanag",3,20}}},{"cwr3_b_vest_alice_light",{{"CUP_NVG_PVS7",1},{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_quikclot",2},{"ACE_CableTie",5},{"ACE_Flashlight_XL50",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_20Rnd_556x45_Stanag",7,20},{"ACE_CTS9",2,1},{"SmokeShellBlue",1,1},{"SmokeShellGreen",1,1}}},{},"cwr3_b_headgear_cap_m81_woodland_early","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_USGuard_Officer_OD_01 : O_USNG_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "o_usguard_od";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_og107_rolled";

        linkedItems[] = {"cwr3_b_vest_alice_officer","H_Beret_02","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_officer","H_Beret_02","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A1","rhsusf_bino_lerca_1200_black"};
        respawnWeapons[] = {"CUP_arifle_M16A1","rhsusf_bino_lerca_1200_black"};

        magazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_20Rnd_556x45_Stanag","CUP_20Rnd_556x45_Stanag"};

        backpack = "B_LegStrapBag_olive_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A1","","","",{"CUP_20Rnd_556x45_Stanag",20},{},""},{},{},{"cwr3_b_uniform_og107_rolled",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_20Rnd_556x45_Stanag",3,20}}},{"cwr3_b_vest_alice_officer",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_20Rnd_556x45_Stanag",9,20},{"ACE_CTS9",2,1},{"SmokeShellBlue",1,1},{"SmokeShellGreen",1,1}}},{"B_LegStrapBag_olive_F",{{"ACE_fieldDressing",5},{"ACE_packingBandage",5},{"ACE_quikclot",2},{"ACE_CableTie",5},{"ACE_Canteen",2},{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1},{"ACE_MapTools",1},{"ACE_morphine",2},{"ACE_splint",2},{"ACE_surgicalKit",1},{"ACE_tourniquet",2}}},"H_Beret_02","",{"rhsusf_bino_lerca_1200_black","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSGuardOD_M38A2_Covered_01 : CUP_B_Ural_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M38A2 (Covered)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_kabina_sla_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_plachta_sla_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\WHL_TyreSize3.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "SLA";

    };

    class O_OUSGuardOD_M38A2_Ammo_01 : CUP_B_Ural_Reammo_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M38A2 (Ammo)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_kabina_sla_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_plachta_sla_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\WHL_TyreSize3.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "SLA";

    };

    class O_OUSGuardOD_M38A2_Fuel_01 : CUP_B_Ural_Refuel_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M38A2 (Fuel)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_kabina_sla_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_open_sla_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_fuel_chdkz_co.paa'];_unit setObjectTextureGlobal [3,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\WHL_TyreSize3.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "SLA";

    };

    class O_OUSGuardOD_M38A2_Open_01 : CUP_B_Ural_Open_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M38A2 (Open)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_kabina_sla_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\ural_open_sla_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Ural\data\WHL_TyreSize3.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "SLA";

    };

    class O_OUSGuardOD_M223_Unarmed_01 : CUP_B_Tigr_233011_GREEN_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M223 (Unarmed)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";

        class Turrets : Turrets {
            class MainTurretTurnIn : MainTurretTurnIn { gunnerType = ""; };
            class MainTurretFFV : MainTurretFFV { gunnerType = ""; };
            class SecTurretTurnIn : SecTurretTurnIn { gunnerType = ""; };
            class SecTurretFFV : SecTurretFFV { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\CarBody_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\HoodOld_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\grille_co.paa'];_unit setObjectTextureGlobal [3,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\ExtraParts_co.paa'];_unit setObjectTextureGlobal [4,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\RoofOld_co.paa'];_unit setObjectTextureGlobal [5,'#(argb,1,1,1)color(0,0,0,0)'];_unit setObjectTextureGlobal [6,'#(argb,1,1,1)color(0,0,0,0)'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Generic_Civil_02";

    };

    class O_OUSGuardOD_M223_Armed_01 : CUP_B_Tigr_233014_PK_GREEN_AFU_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "M223 (Armed)";
        side = 0;
        faction = "o_usguard_od";
        crew = "O_USNG_Rifleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_USNG_Rifleman_01"; };
            class MainTurretTurnIn : MainTurretTurnIn { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\CarBody_co.paa'];_unit setObjectTextureGlobal [1,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\HoodOld_co.paa'];_unit setObjectTextureGlobal [2,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\grille_co.paa'];_unit setObjectTextureGlobal [3,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\ExtraParts_co.paa'];_unit setObjectTextureGlobal [4,'CUP\WheeledVehicles\CUP_WheeledVehicles_Tigr\data\camo\Civil_02\RoofNew_co.paa'];_unit setObjectTextureGlobal [5,'#(argb,1,1,1)color(0,0,0,0)'];_unit setObjectTextureGlobal [6,'#(argb,1,1,1)color(0,0,0,0)'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Generic_Civil_02";

    };

};
