class CfgPatches
{
  class WS_M52S_Vest
  {
    author = "wlan0";
    addonRootClass = "WS_Gear";
    requiredAddons[] =
    {
      "MA_Armor",
      "OPTRE_ACE_Compat",
      "OPTRE_FC_ACE_Compat",
    };
    requiredVersion = 0.1;
  }
}

/* -------------------------------------------------------------------------------- *
  Metaitem Definition
  - Defines the definition of the ACE arsenal expanded categories for selecting
    armor options. 
 * -------------------------------------------------------------------------------- */

// Vest Metaitem
class XtdGearModels
{
  class CfgWeapons
  {
    class WS_M52S_Vest_Metaitem
    {
      label = "Wolf Squad M52S";
      options[] =
      {
        "type",
      };
      class type
      {
        label = "Type";
        alwaysSelectable = 1;
        values[] =
        {
          "light",
          "standard",
          "cqb",
          "marksman",
        };
        class light
        {
          label = "Light";
        };
        class standard
        {
          label = "Standard Issue";
        };
        class cqb
        {
          label = "CQB";
        };
        class marksman
        {
          label = "Marksman";
        };
      };
    };
  };
};

 /* -------------------------------------------------------------------------------- *
  Armor Definitions
  - The actual definitions of the armors follow. These will eventually be
    autogenerated by a script, so DO NOT EDIT THEM unless you know what you're doing.
 * -------------------------------------------------------------------------------- */
class CfgWeapons
{
  class ItemInfo;
  class VestItem;
  class V_PlateCarrier1_rgr;
  class WS_M52S_Vest_Base: V_PlateCarrier1_rgr
  {
    scope = 1;
    scopeArsenal = 1;
    author = "wlan0";
    dlc = "WS";
    displayName = "[WS] M52S Armor";
    model = "MA_Armor\data\Vests\M52_ODST\M52_ODST_Vest.p3d";
    picture = "";
    hiddenSelections[] =
    {
      "Camo1",
      "Camo2",
      "Camo3",
      "Camo4",
      "Camo5",
      "Camo6",
      "Camo7",
      "Camo8",
      "Camo9",
      "Camo10",
      "Camo11",
      "Camo12",
      "Camo13",
      "Camo14",
      "Camo15",
      "Camo16",
      "Camo17",
      "Camo18",
      "Camo19",
      "Camo20",
      "Camo21",
      "Camo22",
      "Camo23",
      "Camo24",
      "Camo25",
      "Camo26",
      "Camo27",
      "Camo28",
      "Camo29",
      "CQB_Left",
      "CQB_Right",
      "Marksman_Left",
      "Marksman_Right",
      "ODST_Bracer_Left",
      "ODST_Bracer_Right",
      "ODST_Chest",
      "ODST_Left",
      "ODST_Right",
      "ChestPMLeft",
      "ChestPMRight",
      "ChestPouch",
      "LShoulderRadio",
      "RShoulderRadio",
      "StomachPouch",
      "TorsoPMLeft",
      "TorsoPMRight",
      "TorsoPouch",
      "WaistBack",
      "WaistGLeft",
      "WaistGRight",
      "WaistPLeft",
      "WaistPRight",
      "WaistRLeft",
      "WaistRRight",
      "WaistSLeft",
      "WaistSRight",
      "LegPouchL",
      "LegPouchR"
    };
    hiddenSelectionsTextures[] =
    {
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // Shoulder L: CQB Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // Shoulder R: CQB Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Shoulder L: Marksman Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Shoulder R: Marksman Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // Bracer L: ODST Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // Bracer R: ODST Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // Chest Plate: ODST
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // Shoulder L: ODST Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // Shoulder R: ODST Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag L: Pistol Mag
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag R: Pistol Mag
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Chest Pouch: ChestPouch
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Accessory L: Radio Left
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Accessory R: Radio Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso: 2x Pouch(?)
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso L: Pistol Mag
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso R: Pistol Mag
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Torso: 1x Pouch(?)
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist B: Pouch
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist SL: Grenades
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist SR: Grenades
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist FL: Pouches
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist FR: Pouches
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist BL: Radio
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist BR: Radio
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist SL: Smoke
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist SR: Smoke
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Leg L: LegPouchL
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa"             // Leg R: LegPouchR
    };
    class ItemInfo: VestItem
    {
      vestType = "Rebreather";
      hiddenSelections[] =
      {
        "Camo1",
        "Camo2",
        "Camo3",
        "Camo4",
        "Camo5",
        "Camo6",
        "Camo7",
        "Camo8",
        "Camo9",
        "Camo10",
        "Camo11",
        "Camo12",
        "Camo13",
        "Camo14",
        "Camo15",
        "Camo16",
        "Camo17",
        "Camo18",
        "Camo19",
        "Camo20",
        "Camo21",
        "Camo22",
        "Camo23",
        "Camo24",
        "Camo25",
        "Camo26",
        "Camo27",
        "Camo28",
        "Camo29",
        "CQB_Left",
        "CQB_Right",
        "Marksman_Left",
        "Marksman_Right",
        "ODST_Bracer_Left",
        "ODST_Bracer_Right",
        "ODST_Chest",
        "ODST_Left",
        "ODST_Right",
        "ChestPMLeft",
        "ChestPMRight",
        "ChestPouch",
        "LShoulderRadio",
        "RShoulderRadio",
        "StomachPouch",
        "TorsoPMLeft",
        "TorsoPMRight",
        "TorsoPouch",
        "WaistBack",
        "WaistGLeft",
        "WaistGRight",
        "WaistPLeft",
        "WaistPRight",
        "WaistRLeft",
        "WaistRRight",
        "WaistSLeft",
        "WaistSRight",
        "LegPouchL",
        "LegPouchR"
      };
      hiddenSelectionsTextures[] =
      {
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",
        "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa",
        "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",
        "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa",
        "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",
        "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa"
      };
      uniformModel = "MA_Armor\data\Vests\M52_ODST\M52_ODST_Vest.p3d";
      containerClass = "Supply200";
      mass = 20;
      passThrough = 0.1;
      modelSides[] = { 6 };
      class HitpointsProtectionInfo
      {
        class Neck
        {
          hitpointName = "HitNeck";
          armor = 20;
          passThrough = 0.5;
        };
        class Legs
        {
          hitpointName = "HitLegs";
          armor = 20;
          passThrough = 0.5;
        };
        class Arms
        {
          hitpointName = "HitArms";
          armor = 25;
          passThrough = 0.1;
        };
        class Hands
        {
          hitpointName = "HitHands";
          armor = 20;
          passThrough = 0.1;
        };
        class Chest
        {
          hitpointName = "HitChest";
          armor = 35;
          passThrough = 0.1;
        };
        class Diaphragm
        {
          hitpointName = "HitDiaphragm";
          armor = 30;
          passThrough = 0.1;
        };
        class Abdomen
        {
          hitpointName = "HitAbdomen";
          armor = 30;
          passThrough = 0.1;
        };
        class Pelvis
        {
          hitpointName = "HitPelvis";
          armor = 30;
          passThrough = 0.1;
        };
        class Body
        {
          hitpointName = "HitBody";
          passThrough = 0.1;
        };
      };
    };
  };

  class WS_M52S_Vest_Light: WS_M52S_Vest_Base
  {
    // Metaitem link
    class XtdGearInfo
    {
      model = "WS_M52S_Vest_Metaitem";
      type = "light";
    };

    scope = 2;
    scopeArsenal = 2;
    hiddenSelectionsTextures[] =
    {
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // CQB Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // CQB Shoulder Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Marksman Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Marksman Shoulder Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Bracer Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Bracer Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Chest
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // ODST Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // ODST Shoulder Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Chest Pouch
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Mounted Radio Left
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Mounted Radio Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Stomach Big Pouch
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso Pistol Mag Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso Pistol Mag Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Torso Big 2x Pouches
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Back Pouch
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Grenades Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Grenades Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Pouches Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Pouches Right
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist Radio Left
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist Radio Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Smoke Grenades Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Smoke Grenades Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Leg Pouch Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa"             // Leg Pouch Right
    };
    class ItemInfo: ItemInfo
    {
      hiddenSelections[] =
      {
        // Commenting a line out makes it visible on the model
        "Camo1",                // CQB Shoulder Left
        "Camo2",                // CQB Shoulder Right
        "Camo3",                // Marksman Shoulder Left
        "Camo4",                // Marksman Shoulder Right
        "Camo5",                // ODST Bracer Left
        "Camo6",                // ODST Bracer Right
        "Camo7",                // ODST Chest
        "Camo8",                // ODST Shoulder Left
        "Camo9",                // ODST Shoulder Right
        "Camo10",               // Chest Pistol Mag Left
        "Camo11",               // Chest Pistol Mag Right
        "Camo12",               // Chest Pouch
        "Camo13",               // Shoulder Mounted Radio Left
        "Camo14",               // Shoulder Mounted Radio Right
        "Camo15",               // Stomach Big Pouch
        "Camo16",               // Torso Pistol Mag Left
        "Camo17",               // Torso Pistol Mag Right
        "Camo18",               // Torso Big 2x Pouches
        "Camo19",               // Waist Back Pouch
        "Camo20",               // Waist Grenades Left
        "Camo21",               // Waist Grenades Right
        "Camo22",               // Waist Pouches Left
        "Camo23",               // Waist Pouches Right
        "Camo24",               // Waist Radio Left
        "Camo25",               // Waist Radio Right
        "Camo26",               // Waist Smoke Grenades Left
        "Camo27",               // Waist Smoke Grenades Right
        "Camo28",               // Leg Pouch Left
        "Camo29",               // Leg Pouch Right

        "CQB_Left",             // CQB Shoulder Left
        "CQB_Right",            // CQB Shoulder Right
        "Marksman_Left",        // Marksman Shoulder Left
        "Marksman_Right",       // Marksman Shoulder Right
        // "ODST_Bracer_Left",     // ODST Bracer Left
        // "ODST_Bracer_Right",    // ODST Bracer Right
        // "ODST_Chest",           // ODST Chest
        "ODST_Left",            // ODST Shoulder Left
        "ODST_Right",           // ODST Shoulder Right
        "ChestPMLeft",          // Chest Pistol Mag Left
        "ChestPMRight",         // Chest Pistol Mag Right
        "ChestPouch",           // Chest Pouch
        "LShoulderRadio",       // Shoulder Mounted Radio Left
        "RShoulderRadio",       // Shoulder Mounted Radio Right
        "StomachPouch",         // Stomach Big Pouch
        "TorsoPMLeft",          // Torso Pistol Mag Left
        "TorsoPMRight",         // Torso Pistol Mag Right
        "TorsoPouch",           // Torso Big 2x Pouches
        "WaistBack",            // Waist Back Pouch
        "WaistGLeft",           // Waist Grenades Left
        "WaistGRight",          // Waist Grenades Right
        "WaistPLeft",           // Waist Pouches Left
        "WaistPRight",          // Waist Pouches Right
        "WaistRLeft",           // Waist Radio Left
        "WaistRRight",          // Waist Radio Right
        "WaistSLeft",           // Waist Smoke Grenades Left
        "WaistSRight",          // Waist Smoke Grenades Right
        "LegPouchL",            // Leg Pouch Left
        "LegPouchR"             // Leg Pouch Right
      };
    };
  };

  class WS_M52S_Vest_Standard: WS_M52S_Vest_Base
  {
    // Metaitem link
    class XtdGearInfo
    {
      model = "WS_M52S_Vest_Metaitem";
      type = "standard";
    };

    scope = 2;
    scopeArsenal = 2;
    hiddenSelectionsTextures[] =
    {
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // CQB Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_CQB_co.paa",               // CQB Shoulder Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Marksman Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Marksman_co.paa",          // Marksman Shoulder Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Bracer Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Bracer Right
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Vest_co.paa",              // ODST Chest
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // ODST Shoulder Left
      "MA_Armor\data\Vests\M52_ODST\Color_Variants\MA_ODST_Shoulders_co.paa",         // ODST Shoulder Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Chest Pistol Mag Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Chest Pouch
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Mounted Radio Left
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Shoulder Mounted Radio Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Stomach Big Pouch
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso Pistol Mag Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Torso Pistol Mag Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Torso Big 2x Pouches
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Back Pouch
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Grenades Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Grenades Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Pouches Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_A_CO.paa",            // Waist Pouches Right
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist Radio Left
      "MA_Armor\data\Backpacks\ODST_Rucksack\Attachments\Backpack_Radio_ODST_co.paa", // Waist Radio Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Smoke Grenades Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Waist Smoke Grenades Right
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa",            // Leg Pouch Left
      "MA_Armor\data\vests\Marine_Pouches\data\MA_TrooperExtras_B_CO.paa"             // Leg Pouch Right
    };
    class ItemInfo: ItemInfo
    {
      hiddenSelections[] =
      {
        // Commenting a line out makes it visible on the model
        "Camo1",                // CQB Shoulder Left
        "Camo2",                // CQB Shoulder Right
        "Camo3",                // Marksman Shoulder Left
        "Camo4",                // Marksman Shoulder Right
        "Camo5",                // ODST Bracer Left
        "Camo6",                // ODST Bracer Right
        "Camo7",                // ODST Chest
        "Camo8",                // ODST Shoulder Left
        "Camo9",                // ODST Shoulder Right
        "Camo10",               // Chest Pistol Mag Left
        "Camo11",               // Chest Pistol Mag Right
        "Camo12",               // Chest Pouch
        "Camo13",               // Shoulder Mounted Radio Left
        "Camo14",               // Shoulder Mounted Radio Right
        "Camo15",               // Stomach Big Pouch
        "Camo16",               // Torso Pistol Mag Left
        "Camo17",               // Torso Pistol Mag Right
        "Camo18",               // Torso Big 2x Pouches
        "Camo19",               // Waist Back Pouch
        "Camo20",               // Waist Grenades Left
        "Camo21",               // Waist Grenades Right
        "Camo22",               // Waist Pouches Left
        "Camo23",               // Waist Pouches Right
        "Camo24",               // Waist Radio Left
        "Camo25",               // Waist Radio Right
        "Camo26",               // Waist Smoke Grenades Left
        "Camo27",               // Waist Smoke Grenades Right
        "Camo28",               // Leg Pouch Left
        "Camo29",               // Leg Pouch Right

        "CQB_Left",             // CQB Shoulder Left
        "CQB_Right",            // CQB Shoulder Right
        "Marksman_Left",        // Marksman Shoulder Left
        "Marksman_Right",       // Marksman Shoulder Right
        // "ODST_Bracer_Left",     // ODST Bracer Left
        // "ODST_Bracer_Right",    // ODST Bracer Right
        // "ODST_Chest",           // ODST Chest
        // "ODST_Left",            // ODST Shoulder Left
        // "ODST_Right",           // ODST Shoulder Right
        "ChestPMLeft",          // Chest Pistol Mag Left
        "ChestPMRight",         // Chest Pistol Mag Right
        "ChestPouch",           // Chest Pouch
        "LShoulderRadio",       // Shoulder Mounted Radio Left
        "RShoulderRadio",       // Shoulder Mounted Radio Right
        "StomachPouch",         // Stomach Big Pouch
        "TorsoPMLeft",          // Torso Pistol Mag Left
        "TorsoPMRight",         // Torso Pistol Mag Right
        "TorsoPouch",           // Torso Big 2x Pouches
        // "WaistBack",            // Waist Back Pouch
        "WaistGLeft",           // Waist Grenades Left
        "WaistGRight",          // Waist Grenades Right
        // "WaistPLeft",           // Waist Pouches Left
        "WaistPRight",          // Waist Pouches Right
        "WaistRLeft",           // Waist Radio Left
        "WaistRRight",          // Waist Radio Right
        "WaistSLeft",           // Waist Smoke Grenades Left
        // "WaistSRight",          // Waist Smoke Grenades Right
        "LegPouchL",            // Leg Pouch Left
        "LegPouchR"             // Leg Pouch Right
      };
    };
  };
};
