import fs from 'fs';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

//#region Generator Body

function main() {
  console.log('Starting TicTac Generation');
  const start = Date.now();

  const templateStrings = {
    warning: 'AUTOGENERATED FILE. Edit config.cpp.tpl or generator.ts instead. Any changes to this file will be overwritten otherwise.',
    exports: '',
    classes: '',
  };

  // build our execution stats
  const execTime = Date.now() - start;
  const numTicTacs = TicTacs.length;
  const numItems = TicTacs.reduce((acc, tictac) => {
    return acc + tictac.contents.length;
  }, 0);

  // iterate through each tictac and append its definitions onto the template strings as needed
  TicTacs.forEach((tictac) => {
    console.log(`  Generating ${tictac.name} Tic Tac`);
    const sanitizedName = tictac.name.replaceAll(' ', '_').replaceAll('-', '_').replaceAll('|', '_');
    const tictacClassName = `WS_Props_TicTac_${sanitizedName}`;

    // export string (classnames only)
    templateStrings.exports += `\n      "${tictacClassName}",`;

    // class strings (full definition)
    templateStrings.classes +=
      `\n` + `\n  class ${tictacClassName}: WS_Props_TicTac_Empty` + `\n  {` + `\n    scope = 2;` + `\n    displayName = "[WS] Supply Pod (${tictac.name})";`;

    if (tictac.texture) {
      templateStrings.classes += `\n    hiddenSelectionsTextures[] = { "${tictac.texture}" };`;
    }

    if (tictac.preview) {
      templateStrings.classes += `\n    editorPreview = "${tictac.preview}";`;
    }

    if (tictac.eventHandlers) {
      templateStrings.classes += `\n    class EventHandlers : EventHandlers\n    {`;
      tictac.eventHandlers.forEach((handler) => {
        const escapedValue = handler.value
          .replaceAll(`\n`, ' ')
          .replaceAll('"', '""')
          .replace(/\s{2,}/g, ' ')
          .trim();
        templateStrings.classes += `\n      ${handler.type} = "${escapedValue}";`;
      });
      templateStrings.classes += `\n    };`;
    }

    (Object.keys(TicTacItemTypes) as (keyof typeof TicTacItemTypes)[]).forEach((key) => {
      templateStrings.classes += GenerateTransportGroup(tictac, key);
    });
    templateStrings.classes += `\n  };`;
  });

  // write our file out
  const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
  let template = fs.readFileSync(`${SCRIPT_DIR}/config.cpp.tpl`).toString();

  (Object.keys(templateStrings) as (keyof typeof templateStrings)[]).forEach((key) => {
    template = template.replace(`<% ${key} %>`, templateStrings[key]);
  });

  try {
    fs.writeFileSync(`${SCRIPT_DIR}/config.cpp`, template);
  } catch (err) {
    throw err;
  }

  console.log(`Done [ took ${execTime / 1000} seconds | ${numTicTacs} TicTacs | ${numItems} items ]`);
}

//#endregion

//#region Types & Maps

type TicTac = {
  name: string;
  texture?: string;
  eventHandlers?: TicTacEvent[];
  preview?: string;
  contents: TicTacItem[];
};

type TicTacEvent = {
  type: (typeof TicTacEventTypes)[keyof typeof TicTacEventTypes];
  value: string;
};

const TicTacEventTypes = {
  INIT: 'init',
} as const;

type TicTacItem = {
  class: string;
  type: (typeof TicTacItemTypes)[keyof typeof TicTacItemTypes];
  count: number;
};

const TicTacItemTypes = {
  ITEM: 'ITEM',
  WEAPON: 'WEAPON',
  MAGAZINE: 'MAGAZINE',
} as const;

type TransportGroup = {
  container: string;
  class: string;
};

const TransportGroupMap: { [key in keyof typeof TicTacItemTypes]: TransportGroup } = {
  [TicTacItemTypes.ITEM]: {
    container: 'TransportItems',
    class: 'name',
  },
  [TicTacItemTypes.MAGAZINE]: {
    container: 'TransportMagazines',
    class: 'magazine',
  },
  [TicTacItemTypes.WEAPON]: {
    container: 'TransportWeapons',
    class: 'weapon',
  },
};

//#endregion

//#region Helper Methods

/**
 * Takes a tictac def and group type and generates the transport class string for all the associated
 * items.
 * @param tictac A full TicTac definition
 * @param groupType The group type to create the string for
 * @returns A string for the TransportXXXX class formatted for template insertion
 */
function GenerateTransportGroup(tictac: TicTac, groupType: keyof typeof TicTacItemTypes): string {
  const transportGroup: TransportGroup = TransportGroupMap[groupType];

  if (!transportGroup) {
    throw new Error(`    Transport Group ${groupType} does not have a mapping. aborting.`);
  }

  const groupItems = tictac.contents.filter((item) => item.type == groupType);
  if (!groupItems.length) {
    return '';
  }

  console.log(`    Creating ${transportGroup.container}`);
  let transportGroupString = `\n    class ${transportGroup.container}\n    {`;

  groupItems.forEach((item) => {
    console.log(`      ${item.count}x ${item.class}`);
    transportGroupString += `\n      class _xx_${item.class} { ${transportGroup.class} = "${item.class}"; count = ${item.count}; };`;
  });

  transportGroupString += '\n    };';
  return transportGroupString;
}

//#endregion

//#region TicTac Definitions
const TicTacs: TicTac[] = [
  //#region MA40 ICWS (+UGL Variant)
  {
    name: 'MA40',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\ma40.paa',
    eventHandlers: [
      {
        type: TicTacEventTypes.INIT,
        value: `
          if (local (_this select 0)) then {
            (_this select 0) addWeaponWithAttachmentsCargoGlobal [
              [
                "TCP_arifle_MA40",
                "TCP_muzzle_brake_762_01",
                "TCP_acc_pointer_lam_MA40",
                "TCP_optic_EVOSJ1",
                [],
                [],
                ""
              ],
            1];
          };`,
      },
    ],
    contents: [
      { class: 'TCP_36Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 7 },
      { class: 'TCP_36Rnd_762x51_Mag_Dual', type: TicTacItemTypes.MAGAZINE, count: 7 },
    ],
  },
  {
    name: 'MA40 UGL',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\ma40gl.paa',
    eventHandlers: [
      {
        type: TicTacEventTypes.INIT,
        value: `
          if (local (_this select 0)) then {
            (_this select 0) addWeaponWithAttachmentsCargoGlobal [
              [
                "TCP_arifle_MA40_GL",
                "TCP_muzzle_brake_762_01",
                "TCP_acc_pointer_lam_MA40",
                "TCP_optic_EVOSJ1",
                [],
                [],
                ""
              ],
            1];
          };`,
      },
    ],
    contents: [
      { class: 'TCP_36Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 4 },
      { class: 'TCP_36Rnd_762x51_Mag_Dual', type: TicTacItemTypes.MAGAZINE, count: 4 },
      { class: 'TCP_1Rnd_40_Shell_HE', type: TicTacItemTypes.MAGAZINE, count: 10 },
      { class: 'TCP_1Rnd_40_Shell_TD', type: TicTacItemTypes.MAGAZINE, count: 2 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_White', type: TicTacItemTypes.MAGAZINE, count: 2 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_Red', type: TicTacItemTypes.MAGAZINE, count: 2 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_Blue', type: TicTacItemTypes.MAGAZINE, count: 2 },
    ],
  },
  {
    name: 'MA40 | Resupply',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\ma40_ammo.paa',
    contents: [
      { class: 'TCP_36Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 21 },
      { class: 'TCP_36Rnd_762x51_Mag_Dual', type: TicTacItemTypes.MAGAZINE, count: 21 },
      { class: 'TCP_36Rnd_762x51_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 7 },
      { class: 'TCP_36Rnd_762x51_Mag_Tracer_DIM', type: TicTacItemTypes.MAGAZINE, count: 7 },
    ],
  },
  {
    name: 'MA40 UGL | Resupply',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\ma40gl_ammo.paa',
    contents: [
      { class: 'TCP_36Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 7 },
      { class: 'TCP_36Rnd_762x51_Mag_Dual', type: TicTacItemTypes.MAGAZINE, count: 7 },
      { class: 'TCP_36Rnd_762x51_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 3 },
      { class: 'TCP_36Rnd_762x51_Mag_Tracer_DIM', type: TicTacItemTypes.MAGAZINE, count: 3 },

      { class: 'TCP_1Rnd_40_Shell_HE', type: TicTacItemTypes.MAGAZINE, count: 20 },
      { class: 'TCP_1Rnd_40_Shell_TD', type: TicTacItemTypes.MAGAZINE, count: 8 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_White', type: TicTacItemTypes.MAGAZINE, count: 5 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_Red', type: TicTacItemTypes.MAGAZINE, count: 5 },
      { class: 'TCP_1Rnd_40_Shell_Smoke_Blue', type: TicTacItemTypes.MAGAZINE, count: 5 },
      { class: 'TCP_1Rnd_40_Shell_Signal_White', type: TicTacItemTypes.MAGAZINE, count: 3 },
      { class: 'TCP_1Rnd_40_Shell_Signal_Red', type: TicTacItemTypes.MAGAZINE, count: 3 },
      { class: 'TCP_1Rnd_40_Shell_Signal_Green', type: TicTacItemTypes.MAGAZINE, count: 3 },
    ],
  },
  //#endregion

  //#region M7 Submachine Gun
  {
    name: 'M7',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\m7.paa',
    eventHandlers: [
      {
        type: TicTacEventTypes.INIT,
        value: `
          if (local (_this select 0)) then {
            (_this select 0) addWeaponWithAttachmentsCargoGlobal [
              [
                "TCP_SMG_M7",
                "TCP_muzzle_snds_523_01",
                "TCP_acc_pointer_lam_M7",
                "TCP_optic_M5BSLSV_Blue",
                [],
                [],
                ""
              ],
            1];
          };`,
      },
    ],
    contents: [{ class: 'TCP_48Rnd_5x23_Mag', type: TicTacItemTypes.MAGAZINE, count: 7 }],
  },
  {
    name: 'M7 | Resupply',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\m7_ammo.paa',
    contents: [{ class: 'TCP_48Rnd_5x23_Mag', type: TicTacItemTypes.MAGAZINE, count: 21 }],
  },
  //#endregion

  //#region VK78 Commando
  {
    name: 'VK78',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\vk78.paa',
    eventHandlers: [
      {
        type: TicTacEventTypes.INIT,
        value: `
          if (local (_this select 0)) then {
            (_this select 0) addWeaponWithAttachmentsCargoGlobal [
              [
                "TCP_srifle_VK78_Gray",
                "TCP_muzzle_brake_65_01",
                "TCP_rail_ammoCounter_VK78",
                "",
                [],
                [],
                "TCP_bipod_Grip_VK78"
              ],
            1];
          };`,
      },
    ],
    contents: [{ class: 'TCP_20Rnd_65x48_Mag', type: TicTacItemTypes.MAGAZINE, count: 14 }],
  },
  {
    name: 'VK78 | Resupply',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\vk78_ammo.paa',
    contents: [
      { class: 'TCP_20Rnd_65x48_Mag', type: TicTacItemTypes.MAGAZINE, count: 36 },
      { class: 'TCP_20Rnd_65x48_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 8 },
      { class: 'TCP_20Rnd_65x48_Mag_Tracer_DIM', type: TicTacItemTypes.MAGAZINE, count: 8 },
    ],
  },
  //#endregion
  /**
   * BR55 Battle Rifle
   */
  // BR55
  // BR55HB
  // BR55 Resupply

  /**
   * M392 DMR
   */
  // M392 DMR
  // M392 DMR Resupply

  /**
   * M45 Shotgun
   */
  // M45
  // M45E
  // M45 Resupply

  //#region M731 Light Machine Gun
  {
    name: 'M731',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\m731.paa',
    eventHandlers: [
      {
        type: TicTacEventTypes.INIT,
        value: `
          if (local (_this select 0)) then {
            (_this select 0) addWeaponWithAttachmentsCargoGlobal [
              [
                "TCP_LMG_M731",
                "TCP_muzzle_brake_762_02",
                "TCP_acc_carryHandle_M731",
                "TCP_optic_EVOSM",
                [],
                [],
                "bipod_01_F_blk"
              ],
            1];
          };`,
      },
    ],
    contents: [
      { class: 'TCP_LMG_M731', type: TicTacItemTypes.WEAPON, count: 1 },
      { class: 'TCP_optic_EVOSM', type: TicTacItemTypes.ITEM, count: 1 },
      { class: 'TCP_acc_carryHandle_M731', type: TicTacItemTypes.ITEM, count: 1 },
      { class: 'TCP_muzzle_brake_762_02', type: TicTacItemTypes.ITEM, count: 1 },

      { class: 'TCP_100Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 4 },
      { class: 'TCP_100Rnd_762x51_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 4 },
    ],
  },
  {
    name: 'M731 | Resupply',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\m731_ammo.paa',
    contents: [
      { class: 'TCP_100Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 12 },
      { class: 'TCP_100Rnd_762x51_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 12 },
      { class: 'TCP_200Rnd_762x51_Mag', type: TicTacItemTypes.MAGAZINE, count: 6 },
      { class: 'TCP_200Rnd_762x51_Mag_Tracer_Green', type: TicTacItemTypes.MAGAZINE, count: 6 },
    ],
  },
  //#endregion

  /**
   * SRS99CX-S2 Antimaterial Rifle
   */
  // SRS99CX-S2
  // SRS99CX-S2 Resupply

  /**
   * SRM77-S2 Integrally Suppressed Sniper Rifle
   */
  // SRM77-S2
  // SRM77-S2 Resupply

  /**
   * M6 Series Pistol
   */
  // M6G
  // M6C2
  // M6 Resupply

  /**
   * M363 Sticky Detonator
   */
  // M363 Sticky Detonator
  // M363 Sticky Detonator Resupply

  /**
   * M41 "SPNKr" Rocket Launcher
   */
  // M41 "SPNKr" SSR MAV/AW
  // M41 "SPNKr" SSR MAV/AW Resupply

  /**
   * M6/V G/GNR "Spartan Laser"
   */
  // M6/V G/GNR
  // M6/V G/GNR Resupply

  //#region AU-44 Mortar
  {
    name: 'AU-44 Mortar',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\au44.paa',
    contents: [
      { class: 'OPTRE_CSW_AU44_Carry_Baseplate', type: TicTacItemTypes.WEAPON, count: 1 },
      { class: 'OPTRE_CSW_AU44_Mortar_Carry', type: TicTacItemTypes.ITEM, count: 1 },
    ],
  },
  {
    name: 'AU-44 Mortar | Ammunition',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\au44_ammo.paa',
    contents: [
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_shells', type: TicTacItemTypes.MAGAZINE, count: 40 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_Cluster_HE', type: TicTacItemTypes.MAGAZINE, count: 5 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_guided', type: TicTacItemTypes.MAGAZINE, count: 8 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_LG', type: TicTacItemTypes.MAGAZINE, count: 8 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_Smoke_white', type: TicTacItemTypes.MAGAZINE, count: 10 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_Flare_white', type: TicTacItemTypes.MAGAZINE, count: 5 },
      { class: 'OPTRE_CSW_1Rnd_122mm_Mo_IR_Flare_white', type: TicTacItemTypes.MAGAZINE, count: 5 },
    ],
  },
  //#endregion

  // TBD Static MMG/HMG

  //#region Utility Pods
  // Medical
  {
    name: 'Medical',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\medical.paa',
    contents: [{ class: 'OPTRE_Biofoam', type: TicTacItemTypes.ITEM, count: 40 }],
  },
  // Grenades
  // Explosives
  // Drones
  {
    name: 'Recon Drones',
    texture: 'WS_Props\\Tictacs\\_textures\\pods\\drone.paa',
    contents: [
      { class: 'MEU_Raven_Drone_Item', type: TicTacItemTypes.ITEM, count: 1 },
      { class: 'OPTRE_OQ_38_Wren_Drone_Item', type: TicTacItemTypes.ITEM, count: 1 },
      { class: 'OPTRE_OQ40_Minibee_Drone_Black_Item', type: TicTacItemTypes.ITEM, count: 1 },
      { class: 'ACE_UAVBattery', type: TicTacItemTypes.ITEM, count: 6 },
    ],
  },
  //#endregion
];
//#endregion

main();
