class CfgPatches {
    class O_ESArmy_DES {
        units[] = {
            "O_ESArmy_Rifleman_DES_01",
            "O_OESArmyDES_Rifleman_AT_01",
            "O_OESArmyDES_Grenadier_01",
            "O_OESArmyDES_Machine_Gunner_01",
            "O_OESArmyDES_Sniper_01",
            "O_OESArmyDES_Medic_01",
            "O_OESArmyDES_Team_Leader_01",
            "O_OESArmyDES_Squad_Leader_01",
            "O_OESArmyDES_Officer_01",
            "O_OESArmyDES_Driver_01",
            "O_OESArmyDES_Crewman_01",
            "O_OESArmyDES_Crew_Commander_01",
            "O_OESArmyDES_Pilot_01",
            "O_OESArmyDES_Helicopter_Pilot_01",
            "O_OESArmyDES_Rifleman_AA_01",
            "O_OESArmyDES_Paratrooper_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "O_USArmy_DES",
            "B_NASRArmy_WDL",
            "A3_Characters_F",
            "CUP_Creatures_Military_RussiaModern_Uniforms",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "Webs_Footsteps",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_expansion_uk",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "lambs_range",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "AlkFrameWork_Default_UI",
            "CUP_Core",
            "cba_xeh"
        };
        author = "Rick";
        authors[] = {"Rick"};
        addonRootClass = "NASR_Factions";
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.5.2409021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_ESArmy_DES {
        displayName = "[PF] Spanish State";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\Spain_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\Spain_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_ESArmy_DES {
            name = "[PF] Spanish State";

            class Infantry {
                name = "Infantry";

                class o_esarmy_infantry_fireteam_des {
                    name = "Fireteam";
                    side = 0;
                    faction = "o_esarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {5,-5,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OESArmyDES_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Grenadier_01";
                    };
                };

                class o_oesarmydes_infantry_rifle_squad {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "O_ESArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OESArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Grenadier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Medic_01";
                    };
                };

                class o_oesarmydes_infantry_mg_team {
                    name = "MG Team";
                    side = 0;
                    faction = "O_ESArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OESArmyDES_Machine_Gunner_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                };

                class o_oesarmydes_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "O_ESArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OESArmyDES_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                };

                class o_oesarmydes_infantry_weapons_squad {
                    name = "Weapons Squad";
                    side = 0;
                    faction = "O_ESArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OESArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Team_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Machine_Gunner_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ESArmy_Rifleman_DES_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OESArmyDES_Rifleman_AA_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };


    class O_ESArmy_Rifleman_DES_01 : O_Soldier_F_OCimport_02 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",2,20}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,20},{"CUP_30Rnd_762x51_FNFAL_M",3,30},{"rhssaf_mag_br_m75",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"CUP_30Rnd_762x51_FNFAL_M",5,30},{"rhssaf_mag_brd_m83_white",2,1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Rifleman_AT_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","ffaa_armas_c90","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","ffaa_armas_c90","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{"ffaa_armas_c90","","","",{},{},""},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{"cwr3_b_uk_backpack",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"CUP_30Rnd_762x51_FNFAL_M",5,30},{"rhssaf_mag_brd_m83_white",2,1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Grenadier_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","rhs_weap_M320","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","rhs_weap_M320","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","rhs_mag_M441_HE","CUP_30Rnd_762x51_FNFAL_M","rhs_mag_M441_HE"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","rhs_mag_M441_HE","CUP_30Rnd_762x51_FNFAL_M","rhs_mag_M441_HE"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{"rhs_weap_M320","","","",{"rhs_mag_M441_HE",1},{},""},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30},{"rhs_mag_M441_HE",1,1}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{"cwr3_b_uk_backpack",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"CUP_30Rnd_762x51_FNFAL_M",5,30},{"rhssaf_mag_brd_m83_white",2,1},{"rhs_mag_M441_HE",2,1},{"CUP_1Rnd_HE_M203",6,1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Machine_Gunner_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"rhs_weap_fnmag","Binocular"};
        respawnWeapons[] = {"rhs_weap_fnmag","Binocular"};

        magazines[] = {"rhsusf_100Rnd_762x51","rhsusf_100Rnd_762x51"};
        respawnMagazines[] = {"rhsusf_100Rnd_762x51","rhsusf_100Rnd_762x51"};

        backpack = "usm_pack_762x51_ammobelts";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_fnmag","","","",{"rhsusf_100Rnd_762x51",100},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"rhssaf_mag_br_m75",1,1},{"rhsusf_100Rnd_762x51",2,100}}},{"usm_pack_762x51_ammobelts",{{"ACE_elasticBandage",1},{"ACE_epinephrine",2},{"ACE_splint",2},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"rhssaf_mag_brd_m83_white",2,1},{"rhsusf_100Rnd_762x51_m62_tracer",2,100}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Sniper_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_srifle_M24_blk","Binocular"};
        respawnWeapons[] = {"CUP_srifle_M24_blk","Binocular"};

        magazines[] = {"CUP_5Rnd_762x51_M24","CUP_5Rnd_762x51_M24"};
        respawnMagazines[] = {"CUP_5Rnd_762x51_M24","CUP_5Rnd_762x51_M24"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M24_blk","","","optic_KHS_blk",{"CUP_5Rnd_762x51_M24",5},{},"bipod_01_F_blk"},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_5Rnd_762x51_M24",3,5}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"rhssaf_mag_br_m75",1,1},{"CUP_5Rnd_762x51_M24",9,5}}},{"cwr3_b_uk_backpack",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"rhssaf_mag_brd_m83_white",2,1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Medic_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "rhs_medic_bag";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{"rhs_medic_bag",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Team_Leader_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Squad_Leader_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "TFAR_mr3000_bwmod";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{"TFAR_mr3000_bwmod",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_MapTools",1}}},"CUP_H_Ger_M92_Cover","CUP_G_PMC_RadioHeadset",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Officer_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","ffaa_et_suboficial_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","ffaa_et_suboficial_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{},"ffaa_et_suboficial_boina","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Driver_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Driver";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9A1","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9A1","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9A1","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_15Rnd_9x19_M9",3,15}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"CUP_15Rnd_9x19_M9",7,15}}},{},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Crewman_01 : O_OESArmyDES_Driver_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_brilat_casco_tripulacion","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_brilat_casco_tripulacion","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9A1","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9A1","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9A1","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_15Rnd_9x19_M9",3,15}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"CUP_15Rnd_9x19_M9",7,15}}},{},"ffaa_brilat_casco_tripulacion","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Crew_Commander_01 : O_OESArmyDES_Crewman_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crew Commander";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_brilog_suboficial_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_brilog_suboficial_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9A1","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9A1","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9A1","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_15Rnd_9x19_M9",3,15}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"CUP_15Rnd_9x19_M9",7,15}}},{},"ffaa_brilog_suboficial_boina","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Pilot_01 : O_OESArmyDES_Driver_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "ffaa_pilot_her_uniforme_item";

        linkedItems[] = {"CUP_V_B_PilotVest","ffaa_casco_famet_piloto","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"CUP_V_B_PilotVest","ffaa_casco_famet_piloto","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9A1","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9A1","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        backpack = "ACE_NonSteerableParachute";

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9A1","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"ffaa_pilot_her_uniforme_item",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_15Rnd_9x19_M9",2,15}}},{"CUP_V_B_PilotVest",{{"CUP_15Rnd_9x19_M9",7,15}}},{"ACE_NonSteerableParachute",{}},"ffaa_casco_famet_piloto","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Helicopter_Pilot_01 : O_OESArmyDES_Pilot_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Pilot";
        side = 0;
        faction = "o_esarmy_des";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "ffaa_famet_uniforme_item_b";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_casco_famet_crew","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","ffaa_casco_famet_crew","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9A1","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9A1","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9A1","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"ffaa_famet_uniforme_item_b",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"CUP_15Rnd_9x19_M9",6,15}}},{},"ffaa_casco_famet_crew","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Rifleman_AA_01 : O_OESArmyDES_Rifleman_AT_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AA)";
        side = 0;
        faction = "O_ESArmy_DES";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_olive","CUP_H_Ger_M92_Cover","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL5062","CUP_launch_FIM92Stinger","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL5062","CUP_launch_FIM92Stinger","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL5062","","","",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{"CUP_launch_FIM92Stinger","","","",{},{},""},{},{"CUP_U_B_BDUv2_roll2_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",1,30}}},{"cwr3_b_vest_pasgt_lbv_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",4,30},{"rhssaf_mag_br_m75",1,1}}},{"cwr3_b_uk_backpack",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"CUP_30Rnd_762x51_FNFAL_M",5,30},{"rhssaf_mag_brd_m83_white",2,1}}},"CUP_H_Ger_M92_Cover","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

    class O_OESArmyDES_Paratrooper_01 : O_ESArmy_Rifleman_DES_01 {
        author = "Rick";
        scope = 2;
        scopeCurator = 2;
        displayName = "Paratrooper";
        side = 0;
        faction = "O_ESArmy_DES";

        identityTypes[] = {"Head_Euro","LanguageENG_F","FFAA_G_default"};

        uniformClass = "CUP_U_B_BDUv2_roll2_gloves_dirty_Rhodesian";

        linkedItems[] = {"cwr3_b_vest_pasgt_lbv_alice_olive","ffaa_bripac_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_lbv_alice_olive","ffaa_bripac_boina","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_FNFAL_railed","Binocular"};
        respawnWeapons[] = {"CUP_arifle_FNFAL_railed","Binocular"};

        magazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};
        respawnMagazines[] = {"CUP_30Rnd_762x51_FNFAL_M","CUP_30Rnd_762x51_FNFAL_M"};

        backpack = "CUP_B_AlicePack_Khaki";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_FNFAL_railed","","","JCA_optic_AICO_black",{"CUP_30Rnd_762x51_FNFAL_M",20},{},""},{},{},{"CUP_U_B_BDUv2_roll2_gloves_dirty_Rhodesian",{{"FirstAidKit",1},{"ffaa_nvgoggles",1},{"Chemlight_green",1,1},{"CUP_30Rnd_762x51_FNFAL_M",2,20}}},{"cwr3_b_vest_pasgt_lbv_alice_olive",{{"ffaa_granada_alhambra",3,1},{"SmokeShell",1,1},{"SmokeShellGreen",1,1},{"Chemlight_green",1,1},{"rhssaf_mag_br_m75",1,1},{"CUP_30Rnd_762x51_FNFAL_M",7,30}}},{"CUP_B_AlicePack_Khaki",{{"ACE_elasticBandage",5},{"ACE_epinephrine",2},{"ACE_EntrenchingTool",1},{"ACE_CableTie",2},{"ACE_splint",2},{"ACE_salineIV",1},{"ACE_salineIV_250",2},{"ACE_salineIV_500",1},{"ACE_morphine",2},{"dmpMatches",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"dmpCanteenClean",2},{"ACE_MRE_CreamTomatoSoup",1},{"ACE_MRE_MeatballsPasta",1},{"ACE_MRE_BeefStew",1},{"rhssaf_mag_brd_m83_white",2,1},{"CUP_30Rnd_762x51_FNFAL_M",7,30}}},"ffaa_bripac_boina","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_Spain'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_Spain";

    };

};