// this object is used for human readability and easy updates. category separation is not
// important for generation except for making it easier to maintain.
export default Object.freeze({
  primary: [
    ['BR55 SR 9.5 mm', 'TCP_arifle_BR55'],
    ['M392 DMR 7.62 mm', 'TCP_srifle_M392'],
    ['M45 12G', 'TCP_sgun_M45'],
    ['M45E 12G', 'TCP_sgun_M45E'],
    ['M7 SMG 5 mm', 'TCP_SMG_M7'],
    ['M731 LMG 7.62 mm', 'TCP_LMG_M731'],
    ['MA37 ICWS 7.62 mm', 'TCP_arifle_MA37'],
    ['MA37 ICWS GL 7.62 mm', 'TCP_arifle_MA37_GL'],
    ['VK78 Commando 6.5 mm (Black)', 'TCP_srifle_VK78_Gray'],
    ['[1st MEU] SRS99CX-S2 AMR', 'MEU_OPTRE_SRS99C'],
    ['SRM77 S2', 'OPTRE_SRM77_S2'],
  ],
  secondary: [
    ['M6C2 PDWS 12.7 mm', 'TCP_hgun_Pistol_M6C2'],
    ['M6G PDWS 12.7 mm', 'TCP_hgun_Pistol_M6G'],
    ['[MA] M363 Sticky Detonator (Gray)', 'MA_363_Sticky_Detonator_Gray'],
    ['UNSC Knife', 'UNSC_Knife'],
    ['WRS - 2 Constrictor', 'WRS_Weapon_Revolver'],
  ],
  launcher: [
    ['[1st] M41 "Jackhammer" SSR MAV/AW', 'MEU_M41_SSR'],
    ['M6/V G/GNR', 'TCP_launch_M6V'],
    ['[CSW] AU-44 Mortar Baseplate', 'OPTRE_CSW_AU44_Carry_Baseplate'],
    ['[CSW] AU-44 Mortar Tube', 'OPTRE_CSW_AU44_Mortar_Carry'],
  ],
  sight: [
    ['Battlerifle Classic Scope', 'OPTRE_BR_Classic_Scope'],
    ['Battlrifle Classic Scope (w/ SLS)', 'OPTRE_BR_Classic_Scope_SLS'],
    ['BR55 A2 Scope', 'OPTRE_BR55HB_Scope'],
    ['BR45 A3 Scope', 'OPTRE_BR45_Scope'],
    ['Oracle N-variant SRS99C Scope', 'OPTRE_SRS99C_Scope_v2'],
    ['M27 RCO', 'TCP_optic_M27RCO'],
    ['M43 RCO', 'TCP_optic_M43RCO'],
    ['M43 RCO (CRS)', 'TCP_optic_M43RCO_CRS'],
    ['M43 RCO (CRS, Eyecup)', 'TCP_optic_M43RCO_CRS_CUP'],
    ['M43 RCO (Eyecup)', 'TCP_optic_M43RCO_CUP'],
    ['M5B SLS/V (Blue)', 'TCP_optic_M5BSLSV_Blue'],
    ['M5B SLS/V (Red)', 'TCP_optic_M5BSLSV'],
    ['M11V ERO (Blue)', 'TCP_optic_M11VERO_Blue'],
    ['M11V ERO (Red)', 'TCP_optic_M11VERO'],
    ['M81 ERO (Blue)', 'TCP_optic_M81ERO_Blue'],
    ['M81 ERO (Red)', 'TCP_optic_M81ERO'],
    ['M884 WSD "EVOS-J GEN II"', 'TCP_optic_EVOSJ1'],
    ['M45 DMO "EVOS-D"', 'TCP_optic_EVOSD'],
    ['KFA-2 (M6G)', 'TCP_optic_KFA_M6G'],
    ['SRM77 Scope', 'OPTRE_SRM_Sight'],
  ],
  rail: [
    ['M12 Laser Aiming Module', 'OPTRE_M12_Laser'],
    ['Flashlight (Max)', 'acc_flashlightMax'],
    ['Torchlite 2401 (M392)', 'TCP_acc_flashlight_M392'],
    ['AN/PEQ-49 LAM (SS/M49)', 'TCP_acc_pointer_lam_M7'],
    ['Carry Handle (M731)', 'TCP_acc_carryHandle_M731'],
    ['M882 LAM "EVOS-J GEN I"', 'TCP_acc_pointer_lam_MA37'],
    ['M44 WSD', 'TCP_rail_ammoCounter_VK78'],
    ['CRL-33V (M45)', 'TCP_acc_flashlight_M45'],
    ['AN/PEQ-6C/S LLM (M6C2 SOCOM)', 'TCP_acc_pointer_lam_M6C2'],
    ['AN/PEQ-6G/L IAM (M6G)', 'TCP_acc_pointer_lam_M6G'],
    ['AN/PEQ-6G/F IAM (M6G)', 'TCP_acc_flashlight_M6G'],
  ],
  muzzle: [
    ['SRS99D Suppressor', 'OPTRE_SRS99D_Suppressor'],
    ['Flash Hider (9.5 mm)', 'TCP_muzzle_flash_95_01'],
    ['Type 2C Flash Hider (9.5 mm)', 'TCP_muzzle_flash_95_02'],
    ['Sound Suppressor (9.5 mm)', 'TCP_muzzle_snds_95_01'],
    ['SS/M49 Suppressor (5 mm)', 'TCP_muzzle_snds_523_01'],
    ['Muzzle Brake (6.5 mm)', 'TCP_muzzle_brake_65_01'],
    ['Flash Hider (7.62 mm)', 'TCP_muzzle_flash_762_01'],
    ['Type 1A Muzzle Brake (7.62 mm)', 'TCP_muzzle_brake_762_01'],
    ['Type 1B Muzzle Brake (7.62 mm)', 'TCP_muzzle_brake_762_03'],
    ['Type 2 Muzzle Brake (7.62 mm)', 'TCP_muzzle_brake_762_02'],
    ['Sound Suppressor (7.62 mm)', 'TCP_muzzle_snds_762_01'],
    ['SOCOM Suppressor [M6C2] (12.7 mm)', 'TCP_muzzle_snds_127_01'],
  ],
  bipod: [
    ['Bipod (Black) [NATO]', 'bipod_01_F_blk'],
    ['Bipod (Black) [CSAT]', 'bipod_02_F_blk'],
    ['Bipod (Black) [AAF]', 'bipod_03_F_blk'],
    ['Type 1 Bipod', 'TCP_bipod_01'],
    ['Grip (VK78)', 'TCP_bipod_Grip_VK78'],
    ['Grip [VK78] (Black)', 'TCP_bipod_Grip_VK78_Gray'],
    ['Side Saddle (M45)', 'TCP_bipod_sideSaddle_M45_Slugs'],
    ['Side Saddle (M45)', 'TCP_bipod_sideSaddle_M45_Mixed'],
    ['Side Saddle (M45)', 'TCP_bipod_sideSaddle_M45_Pellets'],
    ['Hand Guard [M6G2] (Black)', 'TCP_bipod_handGuard_M6G2_blk'],
    ['Trigger Guard [M6G2] (Black)', 'TCP_bipod_triggerGuard_M6G2_blk'],
    ['Hand Guard (M6G)', 'TCP_bipod_handGuard_M6G'],
    ['Trigger Guard (M6G)', 'TCP_bipod_triggerGuard_M6G'],
  ],
  mag: [
    ['', 'TCP_36Rnd_95x40_Mag'],
    ['', 'TCP_36Rnd_95x40_Mag_Tracer_Green'],
    ['', 'TCP_36Rnd_95x40_Mag_Tracer_DIM'],
    ['', 'TCP_100Rnd_762x51_Mag'],
    ['', 'TCP_100Rnd_762x51_Mag_Tracer_Green'],
    ['', 'TCP_100Rnd_762x51_Mag_Tracer_DIM'],
    ['', 'TCP_15Rnd_762x51_Mag_BTHP'],
    ['', 'TCP_15Rnd_762x51_Mag_BTHP_Tracer_Green'],
    ['', 'TCP_15Rnd_762x51_Mag_BTHP_Tracer_DIM'],
    ['', 'TCP_15Rnd_762x51_Mag_Dual'],
    ['', 'TCP_15Rnd_762x51_Mag'],
    ['', 'TCP_15Rnd_762x51_Mag_Tracer_Green'],
    ['', 'TCP_15Rnd_762x51_Mag_Tracer_DIM'],
    ['', 'TCP_200Rnd_762x51_Mag'],
    ['', 'TCP_200Rnd_762x51_Mag_Tracer_Green'],
    ['', 'TCP_200Rnd_762x51_Mag_Tracer_DIM'],
    ['', 'TCP_32Rnd_762x51_Mag_Dual'],
    ['', 'TCP_32Rnd_762x51_Mag'],
    ['', 'TCP_32Rnd_762x51_Mag_Tracer_Green'],
    ['', 'TCP_32Rnd_762x51_Mag_Tracer_DIM'],
    ['', 'TCP_48Rnd_5x23_Mag_AP'],
    ['', 'TCP_48Rnd_5x23_Mag_AP_Tracer_Green'],
    ['', 'TCP_48Rnd_5x23_Mag_AP_Tracer_DIM'],
    ['', 'TCP_48Rnd_5x23_Mag_JHP'],
    ['', 'TCP_48Rnd_5x23_Mag_JHP_Tracer_Green'],
    ['', 'TCP_48Rnd_5x23_Mag_JHP_Tracer_DIM'],
    ['', 'TCP_48Rnd_5x23_Mag'],
    ['', 'TCP_48Rnd_5x23_Mag_Tracer_Green'],
    ['', 'TCP_48Rnd_5x23_Mag_Tracer_DIM'],
    ['', 'TCP_60Rnd_5x23_Mag'],
    ['', 'TCP_60Rnd_5x23_Mag_Tracer_Green'],
    ['', 'TCP_60Rnd_5x23_Mag_Tracer_DIM'],
    ['', 'TCP_1Rnd_40_Shell_TD'],
    ['', 'TCP_1Rnd_40_Shell_HE'],
    ['', 'TCP_20Rnd_65x48_Mag'],
    ['', 'TCP_20Rnd_65x48_Mag_Tracer_Green'],
    ['', 'TCP_20Rnd_65x48_Mag_Tracer_DIM'],
    ['', 'TCP_1Rnd_12Gauge_Shell_Pellets'],
    ['', 'TCP_1Rnd_12Gauge_Shell_Slug'],
    ['', 'TCP_12Rnd_127x30_46_Mag'],
    ['', 'TCP_12Rnd_127x30_52_Mag'],
    ['', 'TCP_12Rnd_127x30_52_Mag_Tracer_Green'],
    ['', 'TCP_12Rnd_127x30_46_Mag_Tracer_Green'],
    ['', 'TCP_8Rnd_127x30_52_Mag'],
    ['', 'TCP_8Rnd_127x30_46_Mag'],
    ['', 'TCP_8Rnd_127x30_46_Mag_Tracer_Green'],
    ['', 'TCP_8Rnd_127x30_52_Mag_Tracer_Green'],
    ['', 'TCP_launch_M6V_DummyMagazine_1'],
    ['', 'MA_363_Sticky_Charge'],
    ['', 'OPTRE_4Rnd_145x114_APFSDS_Mag'],
    ['', 'OPTRE_4Rnd_145x114_Mag_APFSDST'],
    ['', 'OPTRE_4Rnd_145x114_HEDP_Mag'],
    ['', 'OPTRE_4Rnd_145x114_Mag_HEDPT'],
    ['', 'OPTRE_4Rnd_145x114_HVAP_Mag'],
    ['', 'OPTRE_4Rnd_145x114_Mag_HVAPT'],
    ['', 'OPTRE_4Rnd_145x114_Mag_SS'],
    ['', 'OPTRE_4Rnd_145x114_Mag_SST'],
    ['', 'OPTRE_M41_Twin_HE'],
    ['', 'OPTRE_M41_Twin_HEAP'],
    ['', 'OPTRE_M41_Twin_HEAT'],
    ['', 'OPTRE_M41_Twin_HEAT_G_AA'],
    ['', 'OPTRE_M41_Twin_HEAT_G'],
    ['', 'OPTRE_M41_Twin_HEAT_SACLOS'],
    ['', 'OPTRE_M41_Twin_HEAT_SALH'],
    ['5Rnd SRM77 Magazine (Tracer)', 'OPTRE_5Rnd_127x99'],
    ['10Rnd SRM77 Magazine (Tracer)', 'OPTRE_10Rnd_127x99'],
    ['6rd LTS cylinder', 'WRS_Revolver_Magazine'],
  ],
  grenade: [
    ['M2 Smoke Grenade (White)', 'OPTRE_M2_Smoke'],
    ['M2 Smoke Grenade (Purple)', 'OPTRE_M2_Smoke_Purple'],
    ['M2 Smoke Grenade (Blue)', 'OPTRE_M2_Smoke_Blue'],
    ['M2 Smoke Grenade (Red)', 'OPTRE_M2_Smoke_Red'],
    ['Chemlight (Hi Green)', 'ACE_Chemlight_HiGreen'],
    ['Chemlight (Ultra-Hi Orange)', 'ACE_Chemlight_UltraHiOrange'],
    ['[1st MEU] 9 Bang', 'MEU_9bang_Mag'],
    ['[1st MEU] Throwable C7', 'MEU_c7_remote_throwable_Mag'],
    ['[1st MEU] Throwable C7 (sticky)', 'MEU_c7_remote_throwable_sticky_Mag'],
    ['[MA] M9 HE-DP Grenade', 'MA_M9_Frag_Mag'],
    ['[1st MEU] Bubble Shield', 'MEU_Deployable_Bubbleshield_mag'],
  ],
  explosive: [
    ['C-7 Explosive Foam', 'C7_Remote_Mag'],
    ['C12 Demolition Charge', 'C12_Remote_Mag'],
    ['M112 Demolition Block', 'DemoCharge_Remote_Mag'],
    ['M154 Anti-Tank Mine', 'UNSCMine_Range_Mag'],
    ['M168 Demolition Pack', 'M168_Remote_Mag'],
    ['M18A1 Claymore', 'ClaymoreDirectionalMine_Remote_Mag'],
    ['M481 SLAM', 'SLAMDirectionalMine_Wire_Mag'],
  ],
  tool: [
    ['[1st] H2 Spotting Scope', 'MEU_H2_Spotting_Scope_Item'],
    ['Chemical Detector (Cover, Black)', 'ChemicalDetector_01_black_F'],
    ['Dead Man"s switch', 'ACE_DeadManSwitch'],
    ['Defusal Kit', 'ACE_DefusalKit'],
    ['Entrenching Tool', 'ACE_EntrenchingTool'],
    ['Fulton MX-991', 'ACE_Flashlight_MX991'],
    ['Kestrel 4500NV', 'ACE_Kestrel4500'],
    ['M57 Firing Device', 'ACE_Clacker'],
    ['Maglite XL50', 'ACE_Flashlight_XL50'],
    ['Map Tools', 'ACE_MapTools'],
    ['Mine Detector', 'MineDetector'],
    ['Notepad', 'acex_intelitems_notepad'],
    ['Range Card', 'ACE_RangeCard'],
    ['Toolkit', 'ToolKit'],
    ['Wirecutter', 'ACE_wirecutter'],
  ],
  misc: [
    ['[1st] Raven Drone', 'MEU_Raven_Drone_Item'],
    ['Biofoam Canister', 'OPTRE_Biofoam'],
    ['Cable Tie', 'ACE_CableTie'],
    ['IR Strobe', 'ACE_IR_Strobe_Item'],
    ['Rope 12.2 meters', 'ACE_rope12'],
    ['Rope 15.2 meters', 'ACE_rope15'],
    ['Rope 18.3 meters', 'ACE_rope18'],
    ['Rope 27.4 meters', 'ACE_rope27'],
    ['Rope 3.2 meters', 'ACE_rope3'],
    ['Rope 36.6 meters', 'ACE_rope36'],
    ['Rope 6.2 meters', 'ACE_rope6'],
    ['Spray Paint (Black)', 'ACE_SpraypaintBlack'],
    ['Spray Paint (Blue)', 'ACE_SpraypaintBlue'],
    ['Spray Paint (Green)', 'ACE_SpraypaintGreen'],
    ['Spray Paint (Red)', 'ACE_SpraypaintRed'],
    ['Spray Paint (White)', 'ACE_SpraypaintWhite'],
    ['Spray Paint (Yellow)', 'ACE_SpraypaintYellow'],
    ['UAV Battery', 'ACE_UAVBattery'],
  ],
  helmet: [
    ['CH252D Helmet', 'WS_CH252D_Helmet_Base'],
    ['CH252D Helmet (Mickelson)', 'WS_CH252D_Helmet_Mickelson'],
    ['CH252D Helmet (Dukova)', 'WS_CH252D_Helmet_Dukova'],
    ['CH252D Helmet (Finch)', 'WS_CH252D_Helmet_Finch'],
    ['CH252D Helmet (Hayes)', 'WS_CH252D_Helmet_Hayes'],
    ['M52E Helmet (Barnes)', 'WS_M52E_Helmet_Barnes'],
    ['M52E Helmet', 'WS_M52E_Helmet_Base'],
    ['S1 Recon Helmet', 'WS_S1_Helmet_Base'],
    ['Bandana (Black)', 'H_Bandanna_gry'],
    ['Bandana (Black) (Headset)', 'H_Bandanna_gry_headset'],
    ['Beret (Black)', 'TCP_H_Beret_Black'],
    ['Boonie Hat (Black)', 'TCP_H_boonieHat_Black'],
    ['Boonie Hat (Black) (Left Fold)', 'TCP_H_boonieHat_Folded_Left_Black'],
    ['Boonie Hat (Black) (Right Fold)', 'TCP_H_boonieHat_Folded_Right_Black'],
    ['Boonie Hat (Black) (Both Fold)', 'TCP_H_boonieHat_Folded_Black'],
    ['Cap (Black)', 'TCP_H_Cap_Black'],
    ['Cap (Black) (Reversed)', 'TCP_H_Cap_Reversed_Black'],
    ['Cap (Gray)', 'TCP_H_Cap_Gray'],
    ['Cap (Gray) (Reversed)', 'TCP_H_Cap_Reversed_Gray'],
    ['Military Cap (Black)', 'H_MilCap_black'],
    ['Military Headset', 'H_HeadSetMilitary'],
    ['Utility Cover (Black)', 'TCP_H_UtilityCover_Black'],
    ['Watch Cap (Black)', 'TCP_H_WatchCap_Black'],
  ],
  uniform: [
    ['[WS] M52 BDU (ONI)', 'WS_Gear_Uniform_M52_ONI'],
    ['[WS] M52 BDU (ODST, Collar)', 'WS_Gear_Uniform_M52_ODST'],
    ['[WS] M52 BDU (ODST, No Collar)', 'WS_Gear_Uniform_M52_ODST_NC'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_ens'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_ca'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hm3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_lt'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_po2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hm1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_hm2'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_po3'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_cpo'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_hmc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_hr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_vehicle_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_cr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_crew_cdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_medical_ha'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_odst_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_hnsc'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_crew_po1'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_engineering_none'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_femme_odst_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_cn'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_engineering_ltjg'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_medical_lcdr'],
    ['ONI Ship Crew Uniform', 'WS_Gear_Uniform_ONICrew_masc_vehicle_hm1'],
  ],
  vest: [
    ['[WS] M43D Armor (CQB)', 'WS_M43D_Vest_CQB'],
    ['[WS] M43D Armor (Marksman)', 'WS_M43D_Vest_Marksman'],
    ['[WS] M43D Armor (Standard)', 'WS_M43D_Vest_Standard'],
    ['[WS] M43D Armor (Barnes)', 'WS_M43D_Vest_Barnes'],
    ['[WS] M43D Armor (Light)', 'WS_M43D_Vest_Light'],
  ],
  backpack: [
    ['AN/PRC-521 [Black]', 'OPTRE_ANPRC_521_Black'],
    ['[MA] M52D Rucksack', 'MA_M52D_Rucksack'],
    ['[MA] M52D Rucksack (Strapless)', 'MA_M52D_Rucksack_Strapless'],
  ],
  facewear: [
    ['[1MEU] Shemagh (OD)', 'MEU_Shemagh'],
    ['[1MEU] Shemagh (Black)', 'MEU_URB_Shemagh'],
    ['[1MEU] Shemagh (Tan)', 'MEU_DES_Shemagh'],
    ['[1MEU] Shemagh (Brown)', 'MEU_BRW_Shemagh'],
    ['[1MEU] Shemagh (White)', 'MEU_SNW_Shemagh'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_1'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_2'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_3'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_4'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_5'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_6'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_7'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_8'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_9'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_10'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_11'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_12'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_13'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_14'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_15'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_16'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_17'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_18'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_19'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_20'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_21'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_22'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_23'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_24'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_25'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_26'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_27'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_28'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_29'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_30'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_31'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_32'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_33'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_34'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_35'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_36'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_37'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_38'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_39'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_40'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_41'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_42'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_43'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_44'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_45'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_46'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_47'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_48'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_49'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_50'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_51'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_52'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_53'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_54'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_55'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_56'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_57'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_58'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_59'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_60'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_61'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_62'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_63'],
    ['[MA] Custom Facewear', 'MA_ODST_CustomFacewear_64'],
    ['[WSD] CH-49 Helmet Scrim (Green)', 'Rogue_MarineScrimGrn'],
    ['[WSD] CH-49 Helmet Scrim (Tan)', 'Rogue_MarineScrimTan'],
    ['[WSD] CH-49 Helmet Scrim (Urban)', 'Rogue_MarineScrim'],
    ['[WSD] M60C ALICE Webbing', 'Rogue_MarineWebbingFW'],
    ['[WSD] TAC/Essentials Pack', 'WSD_MKIV_Essentials_Attachment'],
    ['[WSD] TAC/Left Hook (MKVB)', 'WSD_MKVB_LeftKnife_Attachment'],
    ['[WSD] TAC/Right Cross (MKVB)', 'WSD_MKVB_RightKnife_Attachment'],
    ['[WSD] TAC/Visegrad Patroller', 'WSD_MKIV_Patroller_Attachment'],
    ['[WSD] Tactical/TACPAD', 'WSD_MKVB_TACPAD'],
    ['[WSD] Tactical/UGPS', 'WS_MKVB_UGPS'],
    ['Bandana (Black)', 'G_Bandanna_blk'],
  ],
  nvg: [
    ['[WS] EOD CBRN Attachment', 'WS_Gear_NVG_EODCBRN'],
    ['[WS] EOD CBRN Attachment', 'WS_Gear_NVG_EODCBRN_Barnes'],
    ['[WS] Vacuum Seal Collar', 'WS_Gear_NVG_VacCollar'],
    ['[WS] Visual Implant', 'WS_Gear_NVG_Implant'],
  ],
  bino: [['H-19 Smartfinder', 'OPTRE_Smartfinder']],
  map: [['Map', 'ItemMap']],
  termina: [
    ['GPS', 'ItemGPS'],
    ['UAV Terminal [NATO]', 'B_UavTerminal'],
  ],
  comms: [['AN/PRC-152', 'TFAR_anprc152']],
  navigation: [['Compass', 'ItemCompass']],
  watch: [
    ['[EQ | Defensive] Hardlight Emitter', 'PHEN_Hardlight_Item'],
    ['[EQ | Utility] Holographic Form Emitter', 'PHEN_HFEEquipment_Item'],
    ['[EQ | Threat Scanner] Threat Scanner', 'PHEN_TSEquipment_Item'],
    ['Altimeter Watch', 'ACE_Altimeter'],
    ['FS-797 Analog Watch', 'TCP_Watch'],
    ['Watch', 'ItemWatch'],
  ],
}) as { [property: string]: string[][] };
