class CfgPatches {
    class B_NASRArmy_WDL {
        units[] = {
            "B_NASRArmy_Rifleman_WDL_01",
            "B_NASRArmy_Rifleman_M136_WDL_01",
            "B_NASRArmy_Grenadier_WDL_01",
            "B_NASRArmy_Machine_Gunner_WDL_01",
            "B_NASRArmy_Ammo_Bearer_WDL_01",
            "B_NASRArmy_Marksman_WDL_01",
            "B_NASRArmy_RATELO_WDL_01",
            "B_NASRArmy_Corpsman_WDL_01",
            "B_NASRArmy_Rifleman_AT_WDL_01",
            "B_NASRArmy_Rifleman_AA_WDL_01",
            "B_NASRArmy_Team_Leader_WDL_01",
            "B_NASRArmy_Squad_Leader_WDL_01",
            "B_NASRArmy_Crewman_WDL_01",
            "B_NASRArmy_Pilot_WDL_01",
            "B_NASRArmy_Pilot_Helicopter_WDL_01",
            "B_NASRArmy_Officer_WDL_01",
            "B_NASRArmy_Sniper_WDL_01",
            "B_NASRArmy_Spotter_WDL_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "O_USArmy_DES",
            "A3_Characters_F",
            "CUP_Creatures_Military_RussiaModern_Uniforms",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "Webs_Footsteps",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_expansion_uk",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "lambs_range",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "AlkFrameWork_Default_UI",
            "CUP_Core",
            "cba_xeh"
        };
        author = "[2LT] O'Neill (He/Him)";
        authors[] = {"[2LT] O'Neill (He/Him)"};
        addonRootClass = "NASR_Factions";
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_NASRArmy_WDL {
        displayName = "[PF] North American Socialist Republic";
        side = 1;
        flag = "ca\Ca_E\data\flag_opfor_co.paa";
        icon = "ca\Ca_E\data\flag_opfor_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_NASRArmy_WDL {
            name = "[PF] North American Socialist Republic";

            class Infantry {
                name = "Infantry";

                class b_bnasrarmywdl_infantry_patrol {
                    name = "Patrol";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_M136_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_platoon_hq {
                    name = "Platoon HQ";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_NASRArmy_Officer_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_RATELO_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Corpsman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_NASRArmy_Team_Leader_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Corpsman_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_rifle_squad {
                    name = "Rifle Squad";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_NASRArmy_Squad_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Team_Leader_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Team_Leader_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_M136_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_M136_WDL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Grenadier_WDL_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Marksman_WDL_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Machine_Gunner_WDL_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Machine_Gunner_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_NASRArmy_Sniper_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Spotter_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_anti_tank_team {
                    name = "Anti-Tank Team";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_AT_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_fireteam_marksman {
                    name = "Fireteam (Marksman)";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Team_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_M136_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Marksman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Machine_Gunner_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_fireteam_grenadier {
                    name = "Fireteam (Grenadier)";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Team_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_M136_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Grenadier_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Machine_Gunner_WDL_01";
                    };
                };

                class b_bnasrarmywdl_infantry_anti_air_team {
                    name = "Anti-Air Team";
                    side = 1;
                    faction = "B_NASRArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_AA_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_NASRArmy_Rifleman_WDL_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };


    class B_NASRArmy_Rifleman_WDL_01 : O_Soldier_F_OCimport_02 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Rifleman_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Rifleman_M136_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Rifleman_M136_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (M136)";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","rhs_weap_M136","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","rhs_weap_M136","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{"rhs_weap_M136","","","",{},{},""},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Grenadier_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Grenadier_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_gl","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_gl","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Carbine_GL_Rail","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Carbine_GL_Rail","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_1Rnd_HE_M203","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_1Rnd_HE_M203","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_1Rnd_HE_M203","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_1Rnd_HE_M203","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Carbine_GL_Rail","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{"CUP_1Rnd_HE_M203",1},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_30Rnd_556x45_XM8",3,30}}},{"cwr3_b_vest_pasgt_alice_woodland_gl",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15},{"CUP_1Rnd_HE_M203",3,1}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Machine_Gunner_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Machine_Gunner_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_mg","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_mg","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_SAW_Rail","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_SAW_Rail","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_15Rnd_9x19_M9","CUP_100Rnd_556x45_BetaCMag","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_100Rnd_556x45_BetaCMag","CUP_15Rnd_9x19_M9","CUP_100Rnd_556x45_BetaCMag","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_SAW_Rail","","","JCA_optic_ACOG_black",{"CUP_100Rnd_556x45_BetaCMag",100},{},"bipod_02_F_blk"},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_100Rnd_556x45_BetaCMag",1,100}}},{"cwr3_b_vest_pasgt_alice_woodland_mg",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15},{"CUP_100Rnd_556x45_BetaCMag",2,100}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Ammo_Bearer_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Ammo_Bearer_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ammo Bearer";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_ar","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_ar","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland_ar",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Marksman_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Marksman_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_light","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_light","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Sharpshooter_Rail","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Sharpshooter_Rail","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Sharpshooter_Rail","","","FA_Leupold_Mk6",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_30Rnd_556x45_XM8",3,30}}},{"cwr3_b_vest_pasgt_alice_woodland_light",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_RATELO_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_RATELO_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "RATELO";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "B_RadioBag_01_wdl_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"B_RadioBag_01_wdl_F",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Corpsman_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Corpsman_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Corpsman";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_medic","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_medic","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice_medic";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland_medic",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice_medic",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Rifleman_AT_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Rifleman_AT_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_launch_NLAW","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_launch_NLAW","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{"CUP_launch_NLAW","","","",{},{},""},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Rifleman_AA_WDL_01 : B_NASRArmy_Rifleman_AT_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Rifleman_AA_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AA)";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_launch_FIM92Stinger","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_launch_FIM92Stinger","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{"CUP_launch_FIM92Stinger","","","",{},{},""},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Team_Leader_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Team_Leader_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","TFAR_anprc152","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","TFAR_anprc152","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"cwr3_b_backpack_alice",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_anprc152","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Squad_Leader_WDL_01 : B_NASRArmy_Team_Leader_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Squad_Leader_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_officer","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_officer","rhssaf_helmet_m97_woodland_black_ess_bare","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","CUP_SOFLAM"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","CUP_SOFLAM"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};

        backpack = "B_RadioBag_01_wdl_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland_officer",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"B_RadioBag_01_wdl_F",{}},"rhssaf_helmet_m97_woodland_black_ess_bare","",{"CUP_SOFLAM","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Crewman_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Crewman_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","cwr3_b_headgear_cvc_goggles","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","cwr3_b_headgear_cvc_goggles","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_arifle_XM8_Compact_Rail","CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_arifle_XM8_Compact_Rail","CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9"};

        backpack = "B_LegStrapBag_olive_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Compact_Rail","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_30Rnd_556x45_XM8",3,30}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"B_LegStrapBag_olive_F",{}},"cwr3_b_headgear_cvc_goggles","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Pilot_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Pilot_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "U_I_pilotCoveralls";

        linkedItems[] = {"CUP_V_B_PilotVest","rhsusf_hgu56p_visor","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"CUP_V_B_PilotVest","rhsusf_hgu56p_visor","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        backpack = "rhsusf_eject_Parachute_backpack";

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"U_I_pilotCoveralls",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15}}},{"CUP_V_B_PilotVest",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"rhsusf_eject_Parachute_backpack",{}},"rhsusf_hgu56p_visor","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Pilot_Helicopter_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Pilot_Helicopter_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot (Helicopter)";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_roll_2_gloves";

        linkedItems[] = {"CUP_V_B_PilotVest","rhsusf_hgu56p","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"CUP_V_B_PilotVest","rhsusf_hgu56p","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_roll_2_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15}}},{"CUP_V_B_PilotVest",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{},"rhsusf_hgu56p","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Officer_WDL_01 : B_NASRArmy_Squad_Leader_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Officer_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_gloves";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_officer","rhssaf_helmet_m97_woodland_black_ess","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_woodland_officer","rhssaf_helmet_m97_woodland_black_ess","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","CUP_SOFLAM"};
        respawnWeapons[] = {"CUP_arifle_XM8_Railed","CUP_hgun_M9","CUP_SOFLAM"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};

        backpack = "CUP_B_Kombat_Olive";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Railed","","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_gloves",{{"FirstAidKit",1},{"CUP_30Rnd_556x45_XM8",3,30},{"CUP_15Rnd_9x19_M9",2,15}}},{"cwr3_b_vest_pasgt_alice_woodland_officer",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"CUP_B_Kombat_Olive",{}},"rhssaf_helmet_m97_woodland_black_ess","",{"CUP_SOFLAM","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Sniper_WDL_01 : B_NASRArmy_Rifleman_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Sniper_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_roll_pads_gloves";

        linkedItems[] = {"cwr3_b_vest_alice_light","CUP_H_US_patrol_cap_WDL","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","CUP_H_US_patrol_cap_WDL","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_srifle_M107_Woodland","CUP_hgun_M9","Laserdesignator_03"};
        respawnWeapons[] = {"CUP_srifle_M107_Woodland","CUP_hgun_M9","Laserdesignator_03"};

        magazines[] = {"CUP_10Rnd_127x99_M107","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_10Rnd_127x99_M107","CUP_15Rnd_9x19_M9","Laserbatteries"};
        respawnMagazines[] = {"CUP_10Rnd_127x99_M107","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_10Rnd_127x99_M107","CUP_15Rnd_9x19_M9","Laserbatteries"};

        backpack = "cwr3_b_backpack_alice";

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M107_Woodland","","","CUP_optic_LeupoldMk4_25x50_LRT",{"CUP_10Rnd_127x99_M107",10},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_roll_pads_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_10Rnd_127x99_M107",1,10}}},{"cwr3_b_vest_alice_light",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15},{"CUP_10Rnd_127x99_M107",2,10}}},{"cwr3_b_backpack_alice",{}},"CUP_H_US_patrol_cap_WDL","CUP_FR_NeckScarf",{"Laserdesignator_03","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

    class B_NASRArmy_Spotter_WDL_01 : B_NASRArmy_Sniper_WDL_01 {
        editorPreview = "NASR_Factions\BLUFOR\NASR\previews\B_NASRArmy_Spotter_WDL_01.jpg";
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Spotter";
        side = 1;
        faction = "b_nasrarmy_wdl";

        identityTypes[] = {"Head_NATO","LanguageENG_F","CUP_G_ARMY","NoGlasses"};

        uniformClass = "CUP_U_B_USMC_MCCUU_M81_roll_pads_gloves";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_i_headgear_boonie_rolled_og107","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_i_headgear_boonie_rolled_og107","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_arifle_XM8_Compact_Rail","CUP_hgun_M9","Laserdesignator_03"};
        respawnWeapons[] = {"CUP_arifle_XM8_Compact_Rail","CUP_hgun_M9","Laserdesignator_03"};

        magazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries","CUP_30Rnd_556x45_XM8","CUP_15Rnd_9x19_M9","Laserbatteries"};

        backpack = "B_RadioBag_01_wdl_F";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_XM8_Compact_Rail","CUP_muzzle_snds_XM8","","JCA_optic_ACOG_black",{"CUP_30Rnd_556x45_XM8",30},{},""},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_USMC_MCCUU_M81_roll_pads_gloves",{{"FirstAidKit",1},{"CUP_15Rnd_9x19_M9",2,15},{"CUP_30Rnd_556x45_XM8",3,30}}},{"cwr3_b_vest_alice_light",{{"CUP_HandGrenade_M67",4,1},{"CUP_15Rnd_9x19_M9",1,15}}},{"B_RadioBag_01_wdl_F",{}},"cwr3_i_headgear_boonie_rolled_og107","CUP_FR_NeckScarf",{"Laserdesignator_03","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_NASR_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_NASR_Subdued_Woodland";

    };

};
