class CfgPatches {
    class O_USArmy_DES {
        units[] = {
            "O_OUSArmyDES_Rifleman_01",
            "O_OUSArmyDES_Machine_Gunner_01",
            "O_OUSArmyDES_Grenadier_01",
            "O_OUSArmyDES_Team_Leader_01",
            "O_OUSArmyDES_Squad_Leader_01",
            "O_OUSArmyDES_Officer_01",
            "O_OUSArmyDES_Sniper_01",
            "O_OUSArmyDES_Medic_01",
            "O_OUSArmyDES_Rifleman_AA_01",
            "O_OUSArmyDES_Rifleman_AT_01",
            "O_OUSArmyDES_Spotter_01",
            "O_OUSArmyDES_Crewman_01",
            "O_OUSArmyDES_Pilot_01",
            "O_OUSArmyDES_Ammo_Bearer_01",
            "O_OUSArmyDES_RATELO_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "CUP_Creatures_Military_RussiaModern_Uniforms",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "Webs_Footsteps",
            "tfar_core",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_expansion_uk",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "lambs_range",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "AlkFrameWork_Default_UI",
            "CUP_Core",
            "cba_xeh"
        };
        author = "[2LT] O'Neill (He/Him)";
        authors[] = {"[2LT] O'Neill (He/Him)"};
        addonRootClass = "NASR_Factions";
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_USArmy_DES {
        displayName = "[PF] USA (Army)";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_USArmy_DES {
            name = "[PF] USA (Army)";

            class Infantry {
                name = "Infantry";

                class o_ousarmydes_infantry_fireteam {
                    name = "Fireteam";
                    side = 0;
                    faction = "o_usarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Grenadier_01";
                    };
                };

                class o_ousarmydes_infantry_rifle_squad {
                    name = "Rifle Squad";
                    side = 0;
                    faction = "o_usarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Team_Leader_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Team_Leader_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Machine_Gunner_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Machine_Gunner_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Ammo_Bearer_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Ammo_Bearer_01";
                    };
                };

                class o_ousarmydes_infantry_anti_tank_team {
                    name = "Anti-tank Team";
                    side = 0;
                    faction = "o_usarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_AT_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_01";
                    };
                };

                class o_ousarmydes_infantry_anti_air_team {
                    name = "Anti-air Team";
                    side = 0;
                    faction = "o_usarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_antiair.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_AA_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Rifleman_01";
                    };
                };

                class o_ousarmydes_infantry_sniper_team {
                    name = "Sniper Team";
                    side = 0;
                    faction = "o_usarmy_des";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Sniper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Spotter_01";
                    };
                };

                class o_ousarmydes_infantry_platoon_headquarters {
                    name = "Platoon Headquarters";
                    side = 0;
                    faction = "O_USArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Officer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_RATELO_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Team_Leader_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Medic_01";
                    };
                };

                class o_ousarmydes_infantry_machine_gun_team {
                    name = "Machine Gun Team";
                    side = 0;
                    faction = "O_USArmy_DES";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Machine_Gunner_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_OUSArmyDES_Ammo_Bearer_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };


    class O_OUSArmyDES_Rifleman_01 : O_Soldier_F_OCimport_02 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A2","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};

        backpack = "CUP_B_RUS_Patrol_bag_6E5_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"30Rnd_556x45_Stanag",5,30},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_B_RUS_Patrol_bag_6E5_Desert",{}},"cwr3_b_headgear_m1_desert_6color","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Machine_Gunner_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_mg","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_mg","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_lmg_m249_pip1"};
        respawnWeapons[] = {"CUP_lmg_m249_pip1"};

        magazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};
        respawnMagazines[] = {"CUP_200Rnd_TE4_Red_Tracer_556x45_M249","CUP_200Rnd_TE4_Red_Tracer_556x45_M249"};

        backpack = "usm_pack_abag_m60";

        ALiVE_orbatCreator_loadout[] = {{"CUP_lmg_m249_pip1","","","",{"CUP_200Rnd_TE4_Red_Tracer_556x45_M249",200},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice_mg",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200}}},{"usm_pack_abag_m60",{{"CUP_200Rnd_TE4_Green_Tracer_556x45_M249",1,200}}},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Grenadier_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_gl","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemRadio","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_gl","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemRadio","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2_GL"};
        respawnWeapons[] = {"CUP_arifle_M16A2_GL"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2_GL","","","",{"CUP_30Rnd_556x45_Stanag",30},{"CUP_1Rnd_HE_M203",1},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30},{"CUP_1Rnd_HE_M203",1,1}}},{"cwr3_b_vest_alice_gl",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1},{"CUP_1Rnd_HE_M203",4,1},{"CUP_1Rnd_Smoke_M203",2,1}}},{},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","ItemRadio","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Team_Leader_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A2","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice_light",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"30Rnd_556x45_Stanag",5,30},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",1,1}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"cwr3_b_headgear_m1_desert_6color","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Squad_Leader_01 : O_OUSArmyDES_Team_Leader_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_gl","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_gl","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2_GL"};
        respawnWeapons[] = {"CUP_arifle_M16A2_GL"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203","CUP_30Rnd_556x45_Stanag","CUP_1Rnd_HE_M203"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2_GL","","","",{"CUP_30Rnd_556x45_Stanag",30},{"CUP_1Rnd_HE_M203",1},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30},{"CUP_1Rnd_HE_M203",1,1}}},{"cwr3_b_vest_alice_gl",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",1,1},{"CUP_1Rnd_HE_M203",4,1},{"1Rnd_SmokeBlue_Grenade_shell",1,1},{"1Rnd_SmokeGreen_Grenade_shell",1,1},{"1Rnd_SmokeRed_Grenade_shell",1,1},{"1Rnd_Smoke_Grenade_shell",2,1},{"CUP_30Rnd_556x45_Stanag",7,30}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Officer_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_officer","rhssaf_beret_green","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_officer","rhssaf_beret_green","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_arifle_Colt727","CUP_SOFLAM"};
        respawnWeapons[] = {"CUP_arifle_Colt727","CUP_SOFLAM"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","Laserbatteries","CUP_30Rnd_556x45_Stanag","Laserbatteries"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","Laserbatteries","CUP_30Rnd_556x45_Stanag","Laserbatteries"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Colt727","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30}}},{"cwr3_b_vest_alice_officer",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"rhssaf_beret_green","",{"CUP_SOFLAM","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Sniper_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_boonie_desert_6color","ItemMap","TFAR_fadak","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_boonie_desert_6color","ItemMap","TFAR_fadak","ItemCompass","ACE_Altimeter"};

        weapons[] = {"CUP_srifle_M24_wdl","rhsusf_bino_lerca_1200_tan"};
        respawnWeapons[] = {"CUP_srifle_M24_wdl","rhsusf_bino_lerca_1200_tan"};

        magazines[] = {"CUP_5Rnd_762x51_M24","CUP_5Rnd_762x51_M24"};
        respawnMagazines[] = {"CUP_5Rnd_762x51_M24","CUP_5Rnd_762x51_M24"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M24_wdl","","","hlc_optic_ZF95Base",{"CUP_5Rnd_762x51_M24",5},{},"bipod_02_F_arid"},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_5Rnd_762x51_M24",3,5}}},{"cwr3_b_vest_alice_light",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{},"cwr3_b_headgear_boonie_desert_6color","",{"rhsusf_bino_lerca_1200_tan","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Medic_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_medic","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_medic","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_Colt727"};
        respawnWeapons[] = {"CUP_arifle_Colt727"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "cwr3_b_backpack_m5_medic";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Colt727","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30}}},{"cwr3_b_vest_alice_medic",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"cwr3_b_backpack_m5_medic",{}},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Rifleman_AA_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AA";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2","CUP_launch_FIM92Stinger_Loaded"};
        respawnWeapons[] = {"CUP_arifle_M16A2","CUP_launch_FIM92Stinger_Loaded"};

        magazines[] = {"30Rnd_556x45_Stanag","CUP_Stinger_M","30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","CUP_Stinger_M","30Rnd_556x45_Stanag"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"30Rnd_556x45_Stanag",30},{},""},{"CUP_launch_FIM92Stinger_Loaded","","","",{"CUP_Stinger_M",1},{},""},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice_light",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"30Rnd_556x45_Stanag",5,30},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Rifleman_AT_01 : O_OUSArmyDES_Rifleman_AA_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AT";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2","CUP_launch_NLAW"};
        respawnWeapons[] = {"CUP_arifle_M16A2","CUP_launch_NLAW"};

        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"30Rnd_556x45_Stanag",30},{},""},{"CUP_launch_NLAW","","","",{},{},""},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice_light",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"30Rnd_556x45_Stanag",5,30},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"cwr3_b_headgear_m1_desert_6color","",{},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Spotter_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Spotter";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice_light","usm_bdu_boonie_dcu","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice_light","usm_bdu_boonie_dcu","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_Colt727","rhsusf_bino_lerca_1200_tan"};
        respawnWeapons[] = {"CUP_arifle_Colt727","rhsusf_bino_lerca_1200_tan"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "CUP_B_RUS_Patrol_bag_Desert";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Colt727","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30}}},{"cwr3_b_vest_alice_light",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_B_RUS_Patrol_bag_Desert",{}},"usm_bdu_boonie_dcu","",{"rhsusf_bino_lerca_1200_tan","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Crewman_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","rhsusf_cvc_ess","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_pasgt_alice_od_crew","rhsusf_cvc_ess","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_hgun_M9","Binocular"};
        respawnWeapons[] = {"CUP_hgun_M9","Binocular"};

        magazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};
        respawnMagazines[] = {"CUP_15Rnd_9x19_M9","CUP_15Rnd_9x19_M9"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"CUP_hgun_M9","","","",{"CUP_15Rnd_9x19_M9",15},{},""},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_15Rnd_9x19_M9",3,15}}},{"cwr3_b_vest_pasgt_alice_od_crew",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{},"rhsusf_cvc_ess","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Pilot_01 : O_OUSArmyDES_Crewman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 0;
        faction = "o_usarmy_des";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "cwr3_b_uniform_pilot";

        linkedItems[] = {"Aircrew_vest_2_NH","H_PilotHelmetHeli_O","ItemMap","ItemGPS","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"Aircrew_vest_2_NH","H_PilotHelmetHeli_O","ItemMap","ItemGPS","ItemCompass","ACE_Altimeter"};

        weapons[] = {"Binocular"};
        respawnWeapons[] = {"Binocular"};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "CUP_T10_Parachute_backpack";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"cwr3_b_uniform_pilot",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"Aircrew_vest_2_NH",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"CUP_T10_Parachute_backpack",{}},"H_PilotHelmetHeli_O","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_Ammo_Bearer_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ammo Bearer";
        side = 0;
        faction = "O_USArmy_DES";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_M16A2","Binocular"};
        respawnWeapons[] = {"CUP_arifle_M16A2","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","30Rnd_556x45_Stanag"};

        backpack = "usm_pack_762x51_bandoliers";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_M16A2","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1}}},{"cwr3_b_vest_alice",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"30Rnd_556x45_Stanag",5,30},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"usm_pack_762x51_bandoliers",{}},"cwr3_b_headgear_m1_desert_6color","",{"Binocular","","","",{},{},""},{"ItemMap","","","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_OUSArmyDES_RATELO_01 : O_OUSArmyDES_Rifleman_01 {
        author = "[2LT] O'Neill (He/Him)";
        scope = 2;
        scopeCurator = 2;
        displayName = "RATELO";
        side = 0;
        faction = "O_USArmy_DES";

        identityTypes[] = {"usm_heads_generic","LanguageENG_F","G_usm_generic"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_desert_US";

        linkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_vest_alice","cwr3_b_headgear_m1_desert_6color","ItemMap","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"CUP_arifle_Colt727","Binocular"};
        respawnWeapons[] = {"CUP_arifle_Colt727","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        backpack = "usm_pack_st138_prc77";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_Colt727","","","",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_desert_US",{{"usm_dogtags",1},{"usm_bdu_boonie_des",1},{"CUP_30Rnd_556x45_Stanag",3,30}}},{"cwr3_b_vest_alice",{{"usm_fielddressing",1},{"CUP_NVG_PVS7",1},{"SmokeShell",1,1},{"SmokeShellYellow",1,1},{"HandGrenade",2,1}}},{"usm_pack_st138_prc77",{}},"cwr3_b_headgear_m1_desert_6color","",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};
