class CfgPatches {
    class O_EDArmy {
        units[] = {
            "O_EDArmy_Rifleman_01",
            "O_EDArmy_Rifleman_AA_01",
            "O_EDArmy_Rifleman_AT_01",
            "O_EDArmy_Autorifleman_01",
            "O_EDArmy_Marksman_01",
            "O_EDArmy_Team_Leader_01",
            "O_EDArmy_Squad_Leader_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "universal_uniforms",
            "CUP_Creatures_Military_RussiaModern_Uniforms",
            "lambs_danger",
            "kka3_gestures_ace",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "Webs_Footsteps",
            "lambs_range",
            "tfar_core",
            "hlcweapons_AUG",
            "ace_gforces",
            "ace_movement",
            "ace_medical_feedback",
            "CUP_Creatures_Military_BAF",
            "CUP_Creatures_Military_Germany",
            "CUP_Creatures_Military_NAPA",
            "CUP_Creatures_Military_PMC",
            "CUP_Creatures_Military_Russia",
            "CUP_Creatures_Military_Taki",
            "CUP_Creatures_Military_TakiInsurgents",
            "CUP_Creatures_Military_USMC",
            "cwr3_soldiers_fia",
            "cwr3_soldiers_ru",
            "cwr3_soldiers_us",
            "CUP_Creatures_Military_ACR",
            "CUP_Creatures_Military_CDF",
            "CUP_Creatures_Military_Chedaki",
            "CUP_Creatures_Military_Delta",
            "CUP_Creatures_Military_RACS",
            "CUP_Creatures_Military_SLA",
            "CUP_Creatures_Military_USArmy",
            "cwr3_expansion_uk",
            "cwr3_hot_couple",
            "CUP_Creatures_Military_HIL",
            "CUP_Creatures_Military_Ukraine",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "ace_thermals",
            "lambs_formations",
            "zen_attributes",
            "ace_refuel",
            "CUP_Core",
            "cba_xeh"
        };
        author = "P. Davis";
        authors[] = {"P. Davis"};
        addonRootClass = "NASR_Factions";
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 218.152405 on Stable branch
// Generated with ALiVE version 2.1.6.2410071
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_EDArmy {
        displayName = "[PF] English Directorate";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\UK_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\UK_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_EDArmy {
            name = "[PF] English Directorate";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};

class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };


    class O_EDArmy_Rifleman_01 : O_Soldier_F_OCimport_02 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l85a1","","","CUP_optic_SUSAT",{"CUP_30Rnd_556x45_Stanag_L85",30},{},""},{},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"CUP_30Rnd_556x45_Stanag_L85",10,30},{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68_Net","G_SWDG_low",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Rifleman_AA_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AA)";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l85a1","cwr3_launch_javelin","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l85a1","cwr3_launch_javelin","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_L85","cwr3_javelin_m","CUP_30Rnd_556x45_Stanag_L85"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_L85","cwr3_javelin_m","CUP_30Rnd_556x45_Stanag_L85"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l85a1","","","CUP_optic_SUSAT",{"CUP_30Rnd_556x45_Stanag_L85",30},{},""},{"cwr3_launch_javelin","","","",{"cwr3_javelin_m",1},{},""},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"CUP_30Rnd_556x45_Stanag_L85",10,30},{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68_Net","",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Rifleman_AT_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Net","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l85a1","CUP_launch_NLAW","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l85a1","CUP_launch_NLAW","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l85a1","","","CUP_optic_SUSAT",{"CUP_30Rnd_556x45_Stanag_L85",30},{},""},{"CUP_launch_NLAW","","","",{},{},""},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"CUP_30Rnd_556x45_Stanag_L85",10,30},{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68_Net","",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Autorifleman_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_roll_gloves_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest_sapper","sp_Helmet_Mk5_Cover_DPM68","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest_sapper","sp_Helmet_Mk5_Cover_DPM68","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l86a1","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l86a1","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_60Rnd_556x45_SureFire_Tracer_Yellow","CUP_60Rnd_556x45_SureFire_Tracer_Yellow"};
        respawnMagazines[] = {"CUP_60Rnd_556x45_SureFire_Tracer_Yellow","CUP_60Rnd_556x45_SureFire_Tracer_Yellow"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l86a1","","","CUP_optic_SUSAT",{"CUP_60Rnd_556x45_SureFire_Tracer_Yellow",60},{},""},{},{},{"CUP_U_B_BDUv2_roll_gloves_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest_sapper",{{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1},{"CUP_60Rnd_556x45_SureFire_Tracer_Yellow",4,60}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68","SP_Moustache",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Marksman_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Scrim_1","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68_Scrim_1","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l86a1","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l86a1","rhsusf_bino_leopold_mk4"};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l86a1","","","optic_MRCO",{},{},""},{},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1},{"CUP_30Rnd_556x45_Stanag_L85",10,30}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68_Scrim_1","",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Team_Leader_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","sp_Helmet_Mk5_Cover_DPM68","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l85a1","","","CUP_optic_SUSAT",{"CUP_30Rnd_556x45_Stanag_L85",30},{},""},{},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"CUP_30Rnd_556x45_Stanag_L85",10,30},{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"sp_Helmet_Mk5_Cover_DPM68","SP_Moustache_Ginger",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };

    class O_EDArmy_Squad_Leader_01 : O_EDArmy_Rifleman_01 {
        author = "P. Davis";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_EDArmy";

        identityTypes[] = {"Head_Euro","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_U_B_BDUv2_gloves_dirty_DPM_OD";

        linkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","cwr3_b_uk_headgear_beret_rm","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};
        respawnlinkedItems[] = {"cwr3_b_uk_vest_58webbing_belt_vest","cwr3_b_uk_headgear_beret_rm","ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch"};

        weapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};
        respawnWeapons[] = {"cwr3_arifle_l85a1","rhsusf_bino_leopold_mk4"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag_L85","CUP_30Rnd_556x45_Stanag_L85"};

        backpack = "cwr3_b_uk_backpack";

        ALiVE_orbatCreator_loadout[] = {{"cwr3_arifle_l85a1","","","CUP_optic_SUSAT",{"CUP_30Rnd_556x45_Stanag_L85",30},{},""},{},{},{"CUP_U_B_BDUv2_gloves_dirty_DPM_OD",{{"sp_accessories_gaiters_brown_gloves_leather",1}}},{"cwr3_b_uk_vest_58webbing_belt_vest",{{"CUP_30Rnd_556x45_Stanag_L85",10,30},{"rhs_grenade_m1939e_f_mag",5,1},{"SmokeShell",2,1}}},{"cwr3_b_uk_backpack",{{"ACE_quikclot",20},{"ACE_epinephrine",4},{"ACE_morphine",4},{"ACE_salineIV",1},{"ACE_salineIV_500",2},{"ACE_salineIV_250",4},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_XL50",1}}},"cwr3_b_uk_headgear_beret_rm","SP_Moustache_Brown",{"rhsusf_bino_leopold_mk4","","","",{},{},""},{"ItemMap","ItemGPS","TFAR_fadak","ItemCompass","Itemwatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'NASR_Insignia_English_Directorate_Subdued_Woodland'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "NASR_Insignia_English_Directorate_Subdued_Woodland";

    };
};