// AUTOGENERATED FILE. Edit config.cpp.tpl or tictacs.json instead. This file will be overwritten by the build script.

class CfgPatches
{
  class PF_Gear_TicTacs
  {
    author = "wlan0";
    addonRootClass = "PF_Gear";
    requiredVersion = 0.1;
    units[] =
    {
      "Module_OPTRE_PelicanSupplyDrop",
      "1st_MEU_patch_vehicles_supplypods", // to override 1stMEU and make sure our tictacs don't get overwritten
      "PF_TicTac_Empty",
      "PF_TicTac_Medical",
      "PF_TicTac_Autorifle",
      "PF_TicTac_Combat_Engineer",
    };
    weapons[] = { };
  };
};

class CfgVehicles
{
  class OPTRE_Ammo_SupplyPod_Empty;
  class PF_TicTac_Empty : OPTRE_Ammo_SupplyPod_Empty
  {
    scope = 1;
    dlc = "PF_Plt";
    author = "wlan0";
    displayName = "[PF] Supply Pod (Empty)";
    maximumLoad = 1000000;
    hiddenSelections[] =
    {
      "camo",
    };
    hiddenSelectionsTextures[] =
    {
      "PF_Gear\tictacs\_textures\pods\empty.paa",
    };
    editorPreview = "PF_Gear\tictacs\_textures\previews\empty.jpg";

    class TransportItems { };
    class TransportMagazines { };
    class TransportWeapons { };
  };

  class PF_TicTac_Medical : PF_TicTac_Empty
  {
    scope = 2;
    displayName = "[PF] Supply Pod (Medical)";
    hiddenSelectionsTextures[] =
    {
      "PF_Gear\tictacs\_textures\pods\medical.paa",
    };
    editorPreview = "PF_Gear\tictacs\_textures\previews\medical.jpg";
    class TransportItems
    {
      class _xx_ACE_adenosine { name = "ACE_adenosine"; count = 16; };
      class _xx_ACE_morphine { name = "ACE_morphine"; count = 16; };
      class _xx_ACE_epinephrine { name = "ACE_epinephrine"; count = 16; };
      class _xx_MEU_Medigel_Light { name = "MEU_Medigel_Light"; count = 150; };
      class _xx_ACE_elasticBandage { name = "ACE_elasticBandage"; count = 20; };
      class _xx_OPTRE_Biofoam { name = "OPTRE_Biofoam"; count = 10; };
      class _xx_ACE_salineIV { name = "ACE_salineIV"; count = 5; };
      class _xx_ACE_salineIV_500 { name = "ACE_salineIV_500"; count = 10; };
      class _xx_ACE_salineIV_250 { name = "ACE_salineIV_250"; count = 20; };
      class _xx_ACE_tourniquet { name = "ACE_tourniquet"; count = 16; };
      class _xx_ACE_splint { name = "ACE_splint"; count = 10; };
      class _xx_adv_aceCPR_AED { name = "adv_aceCPR_AED"; count = 1; };
      class _xx_ACE_surgicalKit { name = "ACE_surgicalKit"; count = 2; };
    };
  };

  class PF_TicTac_Autorifle : PF_TicTac_Empty
  {
    scope = 2;
    displayName = "[PF] Supply Pod (Autorifle)";
    hiddenSelectionsTextures[] =
    {
      "PF_Gear\tictacs\_textures\pods\m73.paa",
    };
    editorPreview = "PF_Gear\tictacs\_textures\previews\lmg.jpg";
    class TransportMagazines
    {
      class _xx_MEU_400Rnd_762x51_AP_HV_Box { magazine = "MEU_400Rnd_762x51_AP_HV_Box"; count = 6; };
    };
  };

  class PF_TicTac_Combat_Engineer : PF_TicTac_Empty
  {
    scope = 2;
    displayName = "[PF] Supply Pod (Combat Engineer)";
    hiddenSelectionsTextures[] =
    {
      "PF_Gear\tictacs\_textures\pods\empty.paa",
    };
    editorPreview = "PF_Gear\tictacs\_textures\previews\empty.jpg";
    class TransportMagazines
    {
      class _xx_C7_Remote_Mag { magazine = "C7_Remote_Mag"; count = 10; };
      class _xx_OPTRE_c7_remote_throwable_sticky_mag { magazine = "OPTRE_c7_remote_throwable_sticky_mag"; count = 5; };
      class _xx_MEU_Deployable_Bubbleshield_mag { magazine = "MEU_Deployable_Bubbleshield_mag"; count = 5; };
      class _xx_C12_Remote_Mag { magazine = "C12_Remote_Mag"; count = 2; };
      class _xx_M168_Remote_Mag { magazine = "M168_Remote_Mag"; count = 1; };
    };
  };

  class Module_F;
  class Module_OPTRE_PelicanSupplyDrop : Module_F
  {
    class Arguments
    {
      class box1
      {
        defaultValue = "PF_TicTac_Empty";
        class values
        {
          class pf_pod_none
          {
            name = "none";
            value = "none";
          };
          class pf_pod_random
          {
            name = "Random Supply Pod";
          };
          class pf_pod_medical
          {
            name = "[PF] Supply Pod (Medical)";
            value = "PF_TicTac_Medical";
          };
          class pf_pod_autorifle
          {
            name = "[PF] Supply Pod (Autorifle)";
            value = "PF_TicTac_Autorifle";
          };
          class pf_pod_combat_engineer
          {
            name = "[PF] Supply Pod (Combat Engineer)";
            value = "PF_TicTac_Combat_Engineer";
          };
        };
      };
    };
  };
};
